### ISSUE TITLE
Support the c! exclusive color operator.

### ISSUE THREAD

**Issue by chuckharmston** [scryfall/feedback#1]
Other sites use `c!`to denote "cards that are only these colors". This can be done on Scryfall now, but `c!u` is much nicer than `c:u -c:wbrg`, and `c!wubgm` is nicer than `c:wubgm -c:r`.

Suggested by [/u/SilverElmdor](https://www.reddit.com/user/SilverElmdor) [on Reddit](https://www.reddit.com/r/magicTCG/comments/6432jn/tip_for_brewing_scryfall_lets_you_search_for/dfztwam/).

**Comment by csuhta** [comment]
c! is now available (it's an alias of `:` and `=`) https://scryfall.com/changelog/improvements-to-color-color-identity-operators-138
