### ISSUE TITLE
Missing artist on Samut, the Tested

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#107]
https://scryfall.com/card/hou/144

Artist is Aleksi Briclot.

**Comment by chuckharmston** [comment]
<img width="228" alt="screen shot 2017-06-11 at 20 48 18" src="https://user-images.githubusercontent.com/23885/27016591-4adade6e-4ee7-11e7-8958-16ad1c82cb66.png">

Looks okay here. Thanks for the report!
