### ISSUE TITLE
Alias Aftermath/Split Card Names

### ISSUE THREAD

**Issue by josephprice** [scryfall/feedback#11]
Searching for...
* Start
* Finish
* Start Finish
* Start to Finish

Should show that Aftermath card.

Verbatim user feedback:
Searching for "commit memory" or "commit to memory" brings no hits (and no suggestions, cf. searching for "wear tear"). These search terms should lead to this card. Same for other aftermath cards.

**Comment by csuhta** [comment]
Done! https://scryfall.com/changelog/split-flip-cards-updated-48

**Comment by NilsEnevoldsen** [comment]
Searching [Start to Finish](https://scryfall.com/search?q=start+to+finish) _does not_ find Start//Finish.

Searching [Beck and Call](https://scryfall.com/search?q=beck+and+call) _does_ find Beck//Call.

**Comment by josephprice** [comment]
To clarify, we recently made some large (awesome!) updates to split cards so that each card is a combined object. Great!

This ticket originally was about aliasing Aftermath cards in the popular vocab, e.g. "Commit to Memory." Let's keep it open until we add his aliasing to the Aftermath cards.

**Comment by NilsEnevoldsen** [comment]
Oh, I'm dumb. Searching [beck and call](https://scryfall.com/search?q=beck+and+call) only works because "and" is the and operator. Searching ["beck and call"](https://scryfall.com/search?q=%22beck+and+call%22) fails.

**Comment by csuhta** [comment]
Yes, so:

- When you search for `Start to Finish`, the system checks for `*start*`, `*to*`, and `*finish*` in the name.
- Searching for `Start and Finish` becomes `*start*` `AND` `*finish*`. The `AND` operator is basically a no-op anyway, since AND-ing together the terms is the default search logic.

Names like "Rise and Fall" and "Start to Finish" are community slang. The official card names don't include these words, the card is named both `Start` and `Finish` by the rules, and decklists/Gatherer list the joined card as `Start // Finish`

Making `to` always magical this way would stop people from searching for things like `sens to` to find [Sensei's Divining Top](https://scryfall.com/card/ema/232), but that my be OK. 

One other thing I don't want to do is hard-code 72 special name sequences.

Thoughts?

**Comment by NilsEnevoldsen** [comment]
I think the right thing to do is to have an alias field, and manually populate it with all the split-card names. I don't think calling it "community slang" is accurate. It's officially sanctioned slang.

[AMONKHET DOWN TO BUSINESS, PART 2](http://magic.wizards.com/en/articles/archive/making-magic/amonkhet-down-business-part-2-2017-04-10):
> Split card use a naming structure where the two mini-card names form a "Blank and Blank" expression (e.g. Assault and Battery). For aftermath, we decided to try something different. Since you always use one spell and then the other, **the naming convention we settled on was "Blank to Blank" expressions**.
> 
> The cards were also designed such that if you had enough mana that you could cast both, the two effects had some synergy with one another. For instance, if you have 3BBB, you can both kill a pesky creature and then exile it from the graveyard to get a 2/2 Zombie token. This might be good if the creature has an ability that works in the graveyard like embalm.

[SPLIT (ODDS &) ENDS](http://magic.wizards.com/en/articles/archive/making-magic/split-odds-ends-2006-04-17):
> So we finally have ten gold split cards that we know what colors each half has to be. This leads us to the next step of split card design – the names. Say what? Isn't naming the card near the end of the process, long after design is finished? Normally, yes, but split cards are a special case. You see, in Invasion, we started by making the five cards. **After they were done, I came up with the _____ & _____ convention for the names (don't get me started on the _____ // _____ thing).** We then searched high and low to find five _____ & _____ names that sounded good, made sense with the color combinations and fit the mechanics of the card.
> 
> …
> 
> I knew when we started the split card design for Dissension that we had to use the same technique. The team started brainstorming names. Then we discovered the advantage of having a guy who makes word puzzles on the side (that would be Mark Gottlieb). Mark came into the next meeting with a printing of every combination of _____ & _____ that existed. The team went through the list and circled every one we thought sounded like it could work for a Magic card.
> 
> …
> 
> To give you a little glimpse into what that process was like, let's take a look at Odds & Ends. **(Yes, yes all the official spoilers are going to call it Odds // Ends, but at least one place can use the names as they were actually envisioned. Why has the ampersand been forsaken so?)** To begin, let's look at the card again.

**Comment by csuhta** [comment]
You can now search for `prepare to fight` and friends and it works! All good? :D

**Comment by NilsEnevoldsen** [comment]
`"prepare to fight"` and `"odds and ends"` fail.

**Comment by csuhta** [comment]
Quotes aren't going to work because "to" is not part of the exact card name.

**Comment by josephprice** [comment]
I'm going to close this ticket. We currently support:
* Start
* Finish
* Start Finish
* Start // Finish

We don't support "Start to Finish" but that would imply a larger alias feature than we want to build right now. If there's more cards that come out that use this pattern OR if we see a lot of people searching by that phrase, we may re-evaluate.

**Comment by csuhta** [comment]
We do support `start to finish` (loose words) now, but `"Start to finish"` and `!"Start to Finish"` won't work because `to` is not in the exact card name (which is what the quotes and `!` operator check)

**Comment by josephprice** [comment]
Oh! That's even better. I suspect we'll have very few of that edge case.
