### ISSUE TITLE
Saved Cards Link Button on Saved Cards View: icon alignment issue

### ISSUE THREAD

**Issue by defbyte** [scryfall/feedback#124]
On Saved Cards screen, the button to get your sharing URL has an icon that's misaligned.

**Note: this appears to be a Safari-only issue**
I'm viewing in Safari 10.1.1
Chrome looks ok.

<img width="450" alt="screenshot 2017-06-21 12 37 36" src="https://user-images.githubusercontent.com/338892/27395630-6f502a26-567e-11e7-88bd-7cbca4d4b208.png">

**Comment by gmac** [comment]
ack, thought I'd fixed most of those. It's that darn issue with Safari not supporting flex layout for `button` elements.

**Comment by gmac** [comment]
this is fixed.
