### ISSUE TITLE
Allow searching by watermark

### ISSUE THREAD

**Issue by chuckharmston** [scryfall/feedback#13]
From /u/NexEstVox [on Reddit](https://www.reddit.com/r/magicTCG/comments/6637j9/amonket_searchable_on_scryfall_lovingly/dgfd9i1/):

> For one, the thing I have to use Gatherer for over Scryfall is card watermarks (e.g. Izzet, Mirran, Abzan.) Any chance that's possible for you?

**Comment by josephprice** [comment]
This would be on a printing level, right?

**Comment by gmac** [comment]
For starters, we'll get the following sets seeded with this data: `rav, gpt, dis, ala, con, arb, som, mbs, nph, rtr, gtc, dgm, ktk, frf, dtk` (per http://mtg.wikia.com/wiki/Category:Watermarks). That should be the bulk of cards that used watermarks as a core set mechanic.

**Comment by csuhta** [comment]
MTGJSON has this data, I just ignored that field when I did the initial import.

**Comment by gmac** [comment]
All watermarks by printing ID are here:

[watermarks.json.zip](https://github.com/scryfall/feedback/files/955853/watermarks.json.zip)

Assigning to Corey for import.

**Comment by csuhta** [comment]
This is now available! https://scryfall.com/docs/reference#flavor
