### ISSUE TITLE
BFZ Game Day Promos should be in more specific set

### ISSUE THREAD

**Issue by ClintTCG** [scryfall/feedback#130]
https://scryfall.com/card/pmgd/48
https://scryfall.com/card/pmgd/47

While it's not bad for them to be in pmgd, other game day promos from this era are in their own promo sets.  These particular ones should be in set pbfz rather than pmgd

**Comment by csuhta** [comment]
These have been moved to `PBFZ`, also [Reya Dawnbringer](https://scryfall.com/card/pm10/35) was moved to `PM10` and the `PMGD` set was deleted entirely, now that it's empty. 💃 

For future reference, we're in the (low-priority) process of "evacuating" promotional cards out of the giant slag heap sets like [Prerelease Events](https://scryfall.com/sets/ppre), into more specific sets like `PBFZ`. There's a semi-related ticket at #34
