### ISSUE TITLE
Incorrect multiverse IDs for BFZ lands

### ISSUE THREAD

**Issue by csuhta** [scryfall/feedback#14]
From /u/uwnT4EqdkTq:

We have the multiverse IDs for these lands inverted:

Plains
- [x] 250 and 250a (401985 and 401992)
- [x] 253 and 253a (401986 and 401994)

Island
- [x] 255 and 255a (401922 and 401925)
- [x] 259 and 259a (401919 and 401921)

Swamp
- [x] 261 and 261a (402053 and 402058)
- [x] 262 and 262a (402054 and 402060)

Mountain
- [x] 265 and 265a (401958 and 401962)
- [x] 266 and 266a (401957 and 401959)
- [x] 267 and 267a (401954 and 401956)
- [x] 269 and 269a (401953 and 401960)

Forest
- [x] 270 and 270a (401887 and 401889)
- [x] 271 and 271a (401885 and 401888)
- [x] 273 and 273a (401882 and 401886)
- [x] 274 and 274a (401883 and 401890)

**Comment by gmac** [comment]
Missing card #273?

**Comment by csuhta** [comment]
?

https://scryfall.com/card/bfz/273
https://scryfall.com/card/bfz/273a

**Comment by gmac** [comment]
Ah... the apparent missing 273 is an issue with the Scryfall admin that I've noticed before. I'll file a ticket with the app repo for it. Otherwise, this archival work is done.

**Comment by card-collector** [comment]
Thanks for the updates. Looks like 1 from this set was missed:

- [ ] Swamp 261a - Expected multiverse id 402053

**Comment by gmac** [comment]
Thanks for verifying (and for the helpful checkbox!). BFZ:261a should be fixed now.
