### ISSUE TITLE
[api] bulk download/sets

### ISSUE THREAD

**Issue by broady** [scryfall/feedback#155]
Is there any way to get bulk information about all cards, similar to mtgjson.com?

If not, could you consider adding one?

**Comment by defbyte** [comment]
Could you list a couple bulk request scenarios? Like, all cards in a set? Or all cards ever?

**Comment by broady** [comment]
All cards ever.

My use case is a [telegram bot](https://github.com/broady/mtg/blob/master/telegram/bot.go). Here's what it looks like:
![image](https://user-images.githubusercontent.com/24982/27986815-43f89c30-63d2-11e7-978a-d32e06e8abe2.png)

To switch to scryfall, I'd need to, on each keystroke:

* Download the card name catalog, or use the autocomplete endpoint (these are great, btw)
* Send a request for each card to get their details (to populate the rule text/type/mana cost/etc)

Not ideal. Unfortunately, this can't be done asynchronously, as Telegram doesn't allow you to update the message after it's been sent (i.e, selected by the user).

I currently use [mtgjson](https://github.com/broady/mtg/blob/master/cards/cards.go#L179).

Totally understand if this isn't a use case you want to support, since it kind of bypasses a lot of the cool stuff scryfall is providing.

**Comment by csuhta** [comment]
We're working on adding an endpoint that lets you get all cards in our database without dealing with sets. This endpoint will almost certainly still be be paginated, so you'd need to cache the objects locally (i.e. make your own flatfile export or local database or whatever works best for your Telegram bot)

We probably won't offer direct flatfile/zip exports for the data. We make small changes to card data and images every day, and our live endpoints return the the updated information immediately and that's totally Space Age™ living.

**Comment by broady** [comment]
Sweet, that'd be great. Even better if there's a way to query cards that have been added/changed since a certain timestamp (to keep the local cache up-to-date). I guess that won't work very well for the pricing information.

**Comment by csuhta** [comment]
Presenting an all-cards endpoint, and it's even sorted newest-first! https://scryfall.com/changelog/api-all-cards-and-mana-parsing-endpoints-128 🎉

All good?

**Comment by csuhta** [comment]
Please open new issues if you have additional suggestions/feedback.

**Comment by broady** [comment]
Only just got to using it. Works perfectly. Thank you!
