### ISSUE TITLE
[api] find all printings of a certain card

### ISSUE THREAD

**Issue by broady** [scryfall/feedback#156]
I expected this search query to return multiple printings:

https://api.scryfall.com/cards/search?q=!%22birds%20of%20paradise%22

Is that wrong?

**Comment by defbyte** [comment]
Hi Broady 👋 

If you're looking to get all printing of a cards (or cards), check out "unrolling" syntax here:
https://scryfall.com/docs/reference#unrolling

and example for getting all Birds of Paradise from the API:
https://api.scryfall.com/cards/search?q=%2B%2B%21%22birds%20of%20paradise%22

**Comment by broady** [comment]
awesome, thanks!
