### ISSUE TITLE
[api] expose image DPI

### ISSUE THREAD

**Issue by broady** [scryfall/feedback#157]
Some cards have a lower resolution, even at the "large" image size, or within the same set.

https://img.scryfall.com/cards/large/en/hou/145.jpg
https://img.scryfall.com/cards/large/en/hou/100.jpg
https://img.scryfall.com/cards/large/en/kld/242.jpg

Even the PNGs appear to be upscaled, and not at their original resolution.

Use case: fetch the image with the highest resolution in black border.

**Comment by defbyte** [comment]
For brand new sets, we don't always have the hi-res image source available initially. As the hi-res art become available, we update cards with the more beautiful version.

**Comment by broady** [comment]
Yep, understood, but there's no way to find that out using the API.

For example, Golgari Signet:
https://api.scryfall.com/cards/search?q=%2B%2B%21%22golgari%20signet%22

I just want to get the highest quality image, regardless of set.

Ideally, I'd like to see something like:

```
"original_image": { "url": "...", "width": ..., "height": ... }
```

rather than using small/normal/large/png, which are scaled.

**Comment by defbyte** [comment]
Gotcha, stayed tuned, we should have some update in this arena soon

**Comment by csuhta** [comment]
On the search endpoints, you can use `is:highres` to find only highres prints: 

- Doc: https://scryfall.com/docs/reference#frame
- Ex: https://scryfall.com/search?q=is%3Ahighres+set%3Ahou
- Ex: https://scryfall.com/search?q=%2B%2Bgolgari+signet+is%3Ahighres

We just added a `highres_image` boolean to card objects so you can detect if a card's images will be high quality before you download them: 
  
- Ex: https://api.scryfall.com/cards/mm2/165?format=json&pretty=true

We won't be exposing metadata about the original image we have stored, sorry!

Does that cover everything? 😃

**Comment by broady** [comment]
I think that'll do! Will try it out and report back if there are any issues.

Awesome fast turnaround :)

**Comment by broady** [comment]
Doesn't work so well for searches:

https://api.scryfall.com/cards/search?q=%2B%2B%21%22Golgari%20Signet%22&format=json&pretty=true

(also, how come pretty=true doesn't work?)

**Comment by csuhta** [comment]
- `highres_image` is now included for every card
- `pretty=true` now works for every API method

**Comment by broady** [comment]
So great, thanks!
