### ISSUE TITLE
Incorrect multiverse IDs and collector numbers for Commander 2016 (c16) lands

### ISSUE THREAD

**Issue by card-collector** [scryfall/feedback#16]
- [x] Plains bc7bc42c-1619-43c1-b720-1dafa391391f (338) - Expected multiverse id 420956, expected collector number 339
- [x] Plains 27f8ed5d-a63f-4e8f-8f1a-10bde4fea710 (339) - Expected multiverse id 420955, expected collector number 338
- [x] Island 34052c96-229b-47c3-ada8-b79e622de846 (341) - Expected multiverse id 420959, expected collector number 342
- [x] Island 3b1238c4-dc34-488f-ad4a-308f584d4d75 (342) - Expected multiverse id 420958, expected collector number 341
- [x] Swamp c12c03f3-4d4e-426a-92ed-e605d840fbd5 (344) - Expected multiverse id 420962, expected collector number 345
- [x] Swamp a834bc0c-2676-4901-a928-5de111b4eedc (345) - Expected multiverse id 420961, expected collector number 344
- [x] Mountain 1b9dd110-c03b-4945-9d56-580cebac63fb (347) - Expected multiverse id 420965, expected collector number 348
- [x] Mountain 1dfead05-dd09-4a07-905f-56c3a69a43d5 (348) - Expected multiverse id 420964, expected collector number 347
- [x] Forest 6efcdb56-3f56-46dc-9309-9f5be3100f32 (350) - Expected multiverse id 420968, expected collector number 351
- [x] Forest aa36a925-9be7-45ba-bf55-30f9a25c09c1 (351) - Expected multiverse id 420967, expected collector number 350

**Comment by gmac** [comment]
Should be set.
