### ISSUE TITLE
`t:Assembly-Worker` returns no results

### ISSUE THREAD

**Issue by broady** [scryfall/feedback#160]
via the Reddit thread... https://www.reddit.com/r/magicTCG/comments/59brng/a_better_faster_card_search_scryfall/d987lrh/?st=j4u81zq4&sh=cc38d81b

Looks like it's broken again.

https://scryfall.com/search?q=t%3Aassembly-worker
https://scryfall.com/search?q=t%3A%22assembly-worker%22

https://scryfall.com/search?q=t%3Aassembly+t%3Aworker

**Comment by csuhta** [comment]
Fixed (again). Thanks for reporting!
