### ISSUE TITLE
rarity wrong named

### ISSUE THREAD

**Issue by tooomm** [scryfall/feedback#164]
`Mythic Rare` is called `Mythic` on Scryfall

example on wizards: http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430833

**Comment by csuhta** [comment]
`mythic` is the identifier we chose to use in the search/API. It's easier to type and inspect when it's a single word. I don't think it has caused any confusion.

We do try to spell it out in UI elements, like on the advanced search form: https://scryfall.com/advanced

**Comment by tooomm** [comment]
Oh sure, that's a great approach actually and makes a lot of sense!
Most people would just use "mythic" in the search anyway.

But look, the same card as linked above: https://scryfall.com/card/hou/144
In the upper right you print the rarity in the interface as just `Mythic`. Maybe you want to change that.
I opened the issue exactly because of that. Search is fine. :)

**Comment by csuhta** [comment]
Ah, you're right. Good catch, it's been changed: https://scryfall.com/card/akh/42
