### ISSUE TITLE
Adding watermark

### ISSUE THREAD

**Issue by Vivalzar** [scryfall/feedback#175]
We can now do a lookup of the watermark. It would be cool if the card's watermark was displayed in the full card screen somewhere. And also in the JSON.

**Comment by gmac** [comment]
Good call. Watermark kind of snuck in during a round of data wrangling, and we never really went back through to include it in the UI.

**Comment by gmac** [comment]
This is done. https://scryfall.com/card/rtr/155

**Comment by Vivalzar** [comment]
Thank you very much.
