### ISSUE TITLE
difference between search and api fuzzy search

### ISSUE THREAD

**Issue by broady** [scryfall/feedback#183]
https://scryfall.com/search?q=gideon%trial

this correctly goes to "Gideon of the Trials"

https://api.scryfall.com/cards/search?q=gideon%20trial
total_cards = 1, as expected

but https://api.scryfall.com/cards/named?fuzzy=gideon%20trial says:

> Too many cards match ambiguous name “gideon trial”. Add more words to refine your search.

**Comment by csuhta** [comment]
This now correctly returns Gideon of the Trails: https://api.scryfall.com/cards/named?fuzzy=gideon%20trial&pretty=true

Previous it was getting hung up on this card: https://scryfall.com/card/takh/25
