### ISSUE TITLE
DTK, FRF, BFZ promos with wrong card frames

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#189]
https://scryfall.com/search?q=frame:1993+e:ppre+(in:bfz+OR+in:dtk+OR+in:frf)

I believe every card in this list should be border:2015.

Related to #33 and #34.

**Comment by csuhta** [comment]
Fixed: https://scryfall.com/search?q=%2B%2Bframe%3A2015+e%3Appre+%28in%3Abfz+OR+in%3Adtk+OR+in%3Afrf%29
