### ISSUE TITLE
Consider a darker background for the card grid

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#19]
White borders look odd on a white background. Would a gray look better?

<img width="1264" alt="screen shot 2017-04-20 at 8 37 26 pm" src="https://cloud.githubusercontent.com/assets/222743/25257872/411116ca-2609-11e7-9b84-005c12854b86.png">

<img width="1220" alt="screen shot 2017-04-20 at 8 39 33 pm" src="https://cloud.githubusercontent.com/assets/222743/25257910/822a07c0-2609-11e7-86b8-0d82c15173a2.png">

**Comment by csuhta** [comment]
Added a shadow so that white bordered cards appear better: https://scryfall.com/search?q=is%3Adual

**Comment by NilsEnevoldsen** [comment]
I like it. Thanks.
