### ISSUE TITLE
PSUS, F03 cards with wrong frames

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#192]
https://scryfall.com/card/psus/8
https://scryfall.com/card/psus/11
https://scryfall.com/card/psus/14
https://scryfall.com/card/psus/21
https://scryfall.com/card/psus/22
https://scryfall.com/card/psus/24
https://scryfall.com/card/psus/25
https://scryfall.com/card/psus/26

https://scryfall.com/card/f03/8
https://scryfall.com/card/f03/9

Every card in this list should be border:2003.

**Comment by csuhta** [comment]
Fixed!
