### ISSUE TITLE
More PSUS cards with wrong frames

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#193]
Sorry for missing these in #192. I didn't realize there were duplicates (and triplicates) in PSUS.

https://scryfall.com/card/psus/10
https://scryfall.com/card/psus/19
https://scryfall.com/card/psus/20
https://scryfall.com/card/psus/23
https://scryfall.com/card/psus/27
https://scryfall.com/card/psus/28
https://scryfall.com/card/psus/29
https://scryfall.com/card/psus/30
https://scryfall.com/card/psus/31
https://scryfall.com/card/psus/32

All should be frame:2003.

**Comment by gmac** [comment]
These all should be fixed. https://scryfall.com/search?q=Slith+Firewalker+frame%3A2003

Thanks Nils!
