### ISSUE TITLE
\w does not match a hyphen

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#194]
https://scryfall.com/docs/regular-expressions

> `\w` — A word character: `A–z`, `0–9` and the hyphen `-`

It appears that `\w` does not actually match the hyphen.

[https://scryfall.com/search?q=re:"kin(\w)guard"](https://scryfall.com/search?q=re:"kin(\w)guard")

**Comment by gmac** [comment]
I think this may be a problem with our documentation... In RegEx, word characters are traditionally letters, numbers, and underscore. While hyphen is used to denote character ranges (ie: `A-z`), it's not actually a matched word character (it counts as punctuation, or non-word character `\W`).

Hey @csuhta – any custom tuning in Scryfall that would make hyphen act as a word character?

**Comment by csuhta** [comment]
Turns out it was underscores, not hypens. I've expanded it to include both (although we won't document underscores because that's not important to Oracle text)


https://scryfall.com/search?q=re:%22kin(%5Cw)guard%22
