### ISSUE TITLE
Three cards with wrong reprint characteristic.

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#196]
https://scryfall.com/card/cp3/1 isn't marked as reprint; should be.
https://scryfall.com/card/ori/182 is marked as reprint; shouldn't be.

https://scryfall.com/card/cp2/1 isn't marked as reprint; should be.
https://scryfall.com/card/ktk/82 is marked as reprint; shouldn't be.

https://scryfall.com/card/cp2/3 isn't marked as reprint; should be.
https://scryfall.com/card/ktk/203 is marked as reprint; shouldn't be.

**Comment by csuhta** [comment]
Fixed!

**Comment by csuhta** [comment]
(Also I added a `reprint` field to the JSON objects for cards so you can see directly what the database thinks about a card's reprint status)
