### ISSUE TITLE
Sort by something other than name when only one oracle card is returned

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#198]
When you search for, e.g., `!forest`, the results are sorted by name. Presumably there is some secondary criterion, but I'm not sure what it is. It's similar to set/number, but with exceptions. I suggest sorting by set/number if only one oracle card is returned.

Alternatively, maybe the appropriate thing to do is just to _by default_ secondarily sort by set/number after name. Whether there should be a visual indication of the secondary sort is something I haven't thought about.

**Comment by csuhta** [comment]
The name sorting is, roughly: name ascending, "covered up" ascending, set release date DEcending.

Where "covered up" is an internal flag we have for some kinds of promos and card with low res scans. Essentially we show the prettier and more-recognizable version of each card ahead of promos or cards we don't have good images for.

Does this change your question at all?

**Comment by NilsEnevoldsen** [comment]
Ohhh, the magic must be happening in "covered up". I was wondering why the HOU forest appeared last in `++!forest is:full`. This is not what I expected, nor what personally desire, but now I understand the intent.

**Comment by NilsEnevoldsen** [comment]
Now that basically all cards are hi-res, behavior is pretty much as I would have expected, and I'm happy to close this.
