### ISSUE TITLE
First character of oracle text not copiable when manamoji.

### ISSUE THREAD

**Issue by chuckharmston** [scryfall/feedback#202]
Feedback from [@TheProxyGuy](https://twitter.com/TheProxyGuy):

When the first character of a card's oracle box is a manamoji, its text is not copiable. Perhaps adding a zero-width character before the start of the text would help this?

**Comment by csuhta** [comment]
I don't have this problem: https://csuhta.s3.amazonaws.com/s/AWbXyZtJ.mp4

Perhaps it's browser/OS specific?

**Comment by josephprice** [comment]
I can't reproduce on Mac / Chrome. Used:
https://scryfall.com/card/m12/105

**Comment by csuhta** [comment]
Closing because of age and failure to reproduce this issue
