### ISSUE TITLE
Incorrect multiverse IDs for Amonkhet (akh) lands

### ISSUE THREAD

**Issue by card-collector** [scryfall/feedback#21]
- [x] Plains 250 - Expected multiverse id 426952
- [x] Island 251 - Expected multiverse id 426953
- [x] Swamp 252 - Expected multiverse id 426954
- [x] Mountain 253 - Expected multiverse id 426955
- [x] Forest 254 - Expected multiverse id 426956
- [x] Plains 255 - Expected multiverse id 426957
- [x] Plains 256 - Expected multiverse id 426958
- [x] Plains 257 - Expected multiverse id 426959
- [x] Island 258 - Expected multiverse id 426960
- [x] Island 259 - Expected multiverse id 426961
- [x] Island 260 - Expected multiverse id 426962
- [x] Swamp 261 - Expected multiverse id 426963
- [x] Swamp 262 - Expected multiverse id 426964
- [x] Swamp 263 - Expected multiverse id 426965
- [x] Mountain 264 - Expected multiverse id 426966
- [x] Mountain 265 - Expected multiverse id 426967
- [x] Mountain 266 - Expected multiverse id 426968
- [x] Forest 267 - Expected multiverse id 426969
- [x] Forest 268 - Expected multiverse id 426970
- [x] Forest 269 - Expected multiverse id 426971

**Comment by gmac** [comment]
Thank you for these reports! One favor – when composing these lists, mind formatting each item as `- [ ] Card...` so that we get checkboxes? It's very useful while working through the ticket.

**Comment by gmac** [comment]
should be set. thanks again for the reports.
