### ISSUE TITLE
Sorting in the pricelist view is broken

### ISSUE THREAD

**Issue by doppeldeveloper** [scryfall/feedback#214]
If I open the pricelist view for a set: https://scryfall.com/sets/ktk?as=checklist

And then hit any of the headings to re-sort the content, I get redirected to a search page with an error: https://scryfall.com/search?as=checklist&order=usd

**Comment by csuhta** [comment]
Fixed!

**Comment by doppeldeveloper** [comment]
Wow, that was fast! Nice one. 😃

**Comment by doppeldeveloper** [comment]
@csuhta Is it meant to toggle back and forth between ascending and descending? Right now it just switches to ascending even when I click a column heading the second time.

**Comment by csuhta** [comment]
Right now it only goes one direction for each value, it mirrors the functionality of the "sorted by" dropdown. We're working on bi-directional sorting options separately.

**Comment by doppeldeveloper** [comment]
Thanks, just making sure it wasn't an un-resolved part of the bug. :)
