### ISSUE TITLE
Quoted search strings don't work as expected

### ISSUE THREAD

**Issue by Gonkers** [scryfall/feedback#22]
This search text...
![image](https://cloud.githubusercontent.com/assets/8480646/25367328/e04a7b14-2942-11e7-865c-f95db32f7e2d.png)

results in this...
![image](https://cloud.githubusercontent.com/assets/8480646/25367340/f88f1234-2942-11e7-8fe9-1f3ae2d5465d.png)

when I would expect... 
![image](https://cloud.githubusercontent.com/assets/8480646/25367351/11ae74a8-2943-11e7-8959-114bd81c0695.png)

Thanks

**Comment by josephprice** [comment]
We should escalate. I think a few people have been having this issue.

**Comment by csuhta** [comment]
Quoted strings are now handled correctly, including negation. Thank you for the report!
