### ISSUE TITLE
Card text fonts have odd choices

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#23]
Currently:
 - title text: system font
 - type line text: system font
 - box text: system font (!?)
   - flavor text: MPlantin
   - reminder text: MPlantin
 - stat text: system font

Preferred alternative:
 - title text: Beleren
 - type line text: Beleren
 - box text: MPlantin
   - flavor text: MPlantin
   - reminder text: MPlantin
 - stat text: Matrix

Simpler alternative:
 - title text: system font
 - type line text: system font
 - box text: MPlantin
   - flavor text: MPlantin
   - reminder text: MPlantin
 - stat text: system font

**Comment by NilsEnevoldsen** [comment]
These might be helpful:

 - https://github.com/AlexandreArpin/mtg-font/tree/master/fonts
 - https://github.com/tdascoli/mtg-js/tree/master/app/fonts
 - https://github.com/magarena/magarena/tree/master/resources/cardbuilder/fonts

**Comment by gmac** [comment]
Thanks for the feedback here and on other issues! We use custom webfonts sparingly for performance reasons; also the goal of Scryfall's aesthetic is not to capture the look of a Magic card so much as to present its information cleanly and quickly. We see great beauty in the simple efficiency of system fonts.

Closing this as a `wontfix`.

**Comment by NilsEnevoldsen** [comment]
That's fine. May I propose then removing MPlantin from the reminder text? It looks very odd to mix a sans system font with italic serif font in the same paragraph. In fact, it looks a little odd for reminder and flavor text to be the only serif font on the entire page.
