### ISSUE TITLE
Higher resolution images for AER/AKH

### ISSUE THREAD

**Issue by card-collector** [scryfall/feedback#24]
Not sure if you are interested in higher quality images or not, if so there are some available for AER and AKH from the WOTC surveys.  You can see and obtain the AER images [here](http://imgur.com/a/ituBs), some discussion about them is [here](https://www.reddit.com/r/magicTCG/comments/6831bf/amonkhet_survey/dgvgs1s/).

If you want a zip of either set (minus planeswalker deck cards and basic lands) let me know and I can upload them somewhere.

**Comment by csuhta** [comment]
We have the AER cards, if you would be willing to provide the AKH cards, that would be awesome.

**Comment by card-collector** [comment]
Here are the images from AKH: https://www.dropbox.com/s/w42xsi9gq5d7z6w/AKH%20Images.zip?dl=1

**Comment by csuhta** [comment]
Thank you so, so much! Are the Invocations also available in the survey by chance?

**Comment by card-collector** [comment]
Doesn't look like it unfortunately (or if so they were named differently than the images I was shown in the survey).

**Comment by csuhta** [comment]
Ok, thank you! We'll be deploying these images soon. If you happen to obtain other WOTC set renders from future customer surveys, we would happily accept them in new issues. 💜
