### ISSUE TITLE
Mishra's Workshop Slack Bug

### ISSUE THREAD

**Issue by josephprice** [scryfall/feedback#242]
From user

> hey, We've been using the scryfall bot for a little while and it is REALLY good. Today we hit a little bug (I think). We tried [[mishras work]] and it replied with "More than one card matches this search" dialog. I was confused because that's new to me, didn't know there was another card. So I searched it in the scryfall site, but then it took me directly to mishra's workshop. Is that a bug?

**Comment by josephprice** [comment]
Verified issue.

**Comment by gmac** [comment]
This was picking up Mishra's Toy Workshop as the alternate (https://scryfall.com/card/hho/14). Searching Scryfall would hide this un-card from results by default.
