### ISSUE TITLE
Color identity "at least" operator for finding commanders

### ISSUE THREAD

**Issue by doppeldeveloper** [scryfall/feedback#246]
Scryfall has a `ci:` operator which lets me find cards that work within a particular color identity. This is pretty helpful.

However, sometimes I already have a set of cards and interactions in mind and I want to find an appropriate commander that will let me put them in the same deck together: I need a search keyword at that point that shows me cards that cover *at least* that color identity.

For example, I'm keen on putting *Ensoul Artifact* (blue), *Tezzeret's Touch* (black+blue), *Tezzeret the Schemer* (black+blue), and *Metallurgic Summonings* (blue) together in a deck. The first thing to do would be to look at the commanders that are at least blue-black that care about artifacts, to see what my options are, so I might search for, say: `ci:ub+ is:commander o:artifacts` (where `ci:ub+` means "a color identity of these colors or more"). That search would give me Silas Renn (UB), Breya (RWUB), Sharuum (WUB), and others.

Alternately I'd like to use the new Taigam, and I'm not sure if I'd make him a commander or put him in the 99. I'd search `ci>=uw is:commander` which would let me start looking at the options of commanders I could use for a deck containing the new Taigam. This search should include cards like [Shu Yun](https://scryfall.com/card/frf/52) (and incidentally, cards like him are the reason the `c:uw` search term can't do this job).

I don't have a strong opinion on whether this should acknowledge partner color pairings (e.g. Ravos and Kraum are at least blue white together, but they are not blue white commanders themselves). This is mainly because at the moment there's only 15 partners anyway so I can check them over and then look at all the other options.

**Comment by csuhta** [comment]
Even though it's not strictly the same, I think you can get away with the `c:`/`color:` operator here. 

The color operator is already "at least", because it just checks that something is a particular color, ignoring the other colors https://scryfall.com/search?as=&q=c%3Aw%20o%3Aartifact%20is%3Acommander

Does that work for the most part?

**Comment by doppeldeveloper** [comment]
It does work for the most part, but it's not thorough and I can't be sure of what I'm missing. The primary thing in mind is commanders who have their color identity defined by stuff outside their mana cost:

* [The Fate Reforged clan leaders](https://scryfall.com/search?q=e%3Afrf+is%3Acommander+-t%3Adragon): mono color, but with 2 other colors in their rules text.
* [Bosh, Iron Golem](https://scryfall.com/card/c14/230): colorless, but a red commander who won't show up in `c:r` searches.
* [Samut, Voice of Dissent](https://scryfall.com/card/akh/205): a Naya commander who won't show up in `c:w` searches.
* [Archangel Avacyn](https://scryfall.com/card/soi/5a) who has a red-white color identity because of [her reverse side](https://scryfall.com/card/soi/5b), but [won't show up in `c:rw` searches](https://scryfall.com/search?q=c%3Arw+avacyn).

**Comment by csuhta** [comment]
We made the color system much more powerful! https://scryfall.com/changelog/improvements-to-color-color-identity-operators-138

![tenor](https://user-images.githubusercontent.com/769083/31264187-647a2d6c-aa35-11e7-8206-93e132618dfc.gif)
