### ISSUE TITLE
HarperPrism book promo printings have "reprint" characteristic reversed

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#25]
https://scryfall.com/search?q=%28Arena+OR+Sewers+of+Estark+OR+Windseeker+Centaur+OR+Giant+Badger+OR+Mana+Crypt%29+e%3Apmei+is%3Areprint

These five printings are _not_ reprints.

All subsequent printings _are_ reprints.

**Comment by NilsEnevoldsen** [comment]
Unlike the cards in #9, these five cards appeared as promos _well before_ their non-promo reprints. They were designed as promos first. I support the general principle of #9; these five cards are a [unique?] exception.

**Comment by NilsEnevoldsen** [comment]
Those five are _not_ unique: [Nalathni Dragon](https://scryfall.com/card/pmei/3) also fits in this category. (The promo is listed as a reprint; it shouldn't be.)

**Comment by csuhta** [comment]
You're right about all of this. We should pull the five HarperPrism cards into their own set so they can be identified as originals. Dragon Con's set also (since its only card in Nalathni Dragon)

**Comment by csuhta** [comment]
Done! Images have been improved as well. https://scryfall.com/search?q=%28e%3Aphpr+or+e%3Apdrc%29+not%3Areprint
