### ISSUE TITLE
Filter on Front or Backface

### ISSUE THREAD

**Issue by AluminumAngel** [scryfall/feedback#250]
I would love to be able to filter on whether a card is a backface.  For example, "++e:isd is:transform -is:backface" would show only the front face of Innistrad double-faced cards.

**Comment by csuhta** [comment]
We're planning to eventually merge the transform cards into a single page/record like we've done with the split spells and flip creatures, so the fact that we keep track of the front face or back face of transforming cards separately will be going away.
