### ISSUE TITLE
wrong line breaks / word split on line end

### ISSUE THREAD

**Issue by tooomm** [scryfall/feedback#258]
![untitled](https://user-images.githubusercontent.com/9874850/29560688-24540d36-8733-11e7-827b-f8d951ff939e.png)

**Comment by doppeldeveloper** [comment]
https://scryfall.com/card/hou/36 -- I don't get the same thing:

![chrome_2017-08-22_12-47-00](https://user-images.githubusercontent.com/4585677/29564048-138d5d18-8738-11e7-9549-c58b3f6f30e0.png)

Possibly this is browser-specific "break word" behaviour for word wrapping, but that's kinda weird.

**Comment by tooomm** [comment]
Interesting. Running Firefox 55.0.2

**Comment by tooomm** [comment]
Is this a new problem in recent firefox versions only?
Can side owners work around this?

**Comment by csuhta** [comment]
Fixed
