### ISSUE TITLE
Include parent set code in sets API data

### ISSUE THREAD

**Issue by Yuudaari** [scryfall/feedback#270]
Maybe `/sets/block/:code`
So `/sets/block/kld` would return all sets with the block code "kld", (aether revolt, kaladesh)

This is supported in a competing API https://api.magicthegathering.io/v1/sets?block=Kaladesh

**Comment by gmac** [comment]
This is currently supported using "b:code". For example: https://scryfall.com/search?q=b%3Aisd

**Comment by Yuudaari** [comment]
That's not what I'm looking for, I'm looking to query for *sets* by block, not *cards*.

**Comment by gmac** [comment]
Sorry, read over that detail. We have encountered this request before. The public site has no real concept of presenting sets as records, so this would be API-only... at which time, sets data in the API is slim enough that we'd simply ask that you fetch all sets and filter by block code on your end.

**Comment by Yuudaari** [comment]
Yea, I guess that makes sense =P

**Comment by silasary** [comment]
It would be nice to get a list of linked sets (Sets that appear nested on the `/sets` page)

While `T<setcode>` and `P<setcode>` make sense and can be inferred, others, like `EXP`, `UGIN`, or `CP3` are somewhat arbitrary, and would need to be hard-coded.

![image](https://user-images.githubusercontent.com/194254/29778713-9d32d8fc-8c53-11e7-974c-3839a7ffa395.png)

**Comment by gmac** [comment]
Sure, we could add the parent set code reference into the API data.

**Comment by gmac** [comment]
Actually, looking into this – `parent_set_code` is already available in API data. https://api.scryfall.com/sets
