### ISSUE TITLE
Commander Anothology: Elves vs Goblins Tokens are linked to DDA: Jace vs Chandra.

### ISSUE THREAD

**Issue by silasary** [scryfall/feedback#273]
[https://scryfall.com/sets](https://scryfall.com/sets)
![image](https://user-images.githubusercontent.com/194254/29778765-c0586d2e-8c53-11e7-9448-39bd8d8d91b0.png)

**Comment by gmac** [comment]
Interesting. This doesn't appear to be a data issue (that linkage is set correctly), which makes me think this is an issue with the way that list gets sorted for visual display.

**Comment by gmac** [comment]
Hu, the linked symbol code isn't picking up either.

**Comment by csuhta** [comment]
Fixed
