### ISSUE TITLE
Missing large amount of prerelease promos

### ISSUE THREAD

**Issue by lincolnthree** [scryfall/feedback#278]
Not sure if this is on your radar or not, but seems like some of the pre-release promos are missing. So far Jace, Liliana, Heretical Healer, etc. Not sure what others, those are just what I saw when poking around.

**Comment by Sniffnoy** [comment]
It looks to me like it's all 5 flipwalkers from Magic Origins that are missing, not just those two!  (Note that in the current system these would go in the Magic Origins promos set, PORI, rather than the prerelease promos set, PPRE.)

**Comment by csuhta** [comment]
We're missing a large amount of prerelease promos at the moment. Almost all of them are the barely-unique "date-stamped" foils such as this: https://scryfall.com/search?q=%2B%2Bsiege+rhino+%28e%3Apktk+or+e%3Aktk%29

It's in progress (slowly)…

**Comment by Sniffnoy** [comment]
Oh, good to know, glad this is being worked on!

**Comment by jhallbachner** [comment]
I believe this is now complete. `is:prerelease` will get you a full list of all of these cards, including all the different stamped-pack-foil versions from KTK onwards. `is:datestamped` will also get you a full list of every card with a printed datestamp, which is all but a few of the prerelease cards, all but a slightly larger list of release cards, and the promo Draft Weekend Ramunap Excavator.
