### ISSUE TITLE
Support non-English cards

### ISSUE THREAD

**Issue by bra1n** [scryfall/feedback#283]
Allow querying the API with non-English card names as well as English card names, similar to magiccards.info: http://magiccards.info/query?q=soldat&v=card&s=cname

**Comment by csuhta** [comment]
This is in progress, but it's slow going. I'm co-opting your ticket to track it publicly.

**Comment by spirius44** [comment]
Hi, my french community (300 members)and me would like to know when non-english command will be work. Thanks

**Comment by NilsEnevoldsen** [comment]
@spirius44 It works now! See https://scryfall.com/blog/announcing-multilingual-support-185 and https://scryfall.com/docs/api/languages.

Example searches are https://scryfall.com/search?q=lang:fr and https://api.scryfall.com/cards/search?q=lang:fr

**Comment by NilsEnevoldsen** [comment]
(Also @csuhta this is probably okay to close.)

**Comment by spirius44** [comment]
How it does work on your discord bot please? 

Cordialement,

Frédéric Modine

**Comment by NilsEnevoldsen** [comment]
@spirius44 Ah, the bots aren't fully multilingual capable yet, as far as I know. You can kinda do it with [[grunn the lonely king lang:fr]] (although the preview is in English) or [[!grunn the lonely king lang:fr]]. I know a bot overhaul is in the works. I image multilingual features will be part of that.

**Comment by spirius44** [comment]
Great, but not yet with FR card’s name..?

Cordialement,

Frédéric Modine

**Comment by NilsEnevoldsen** [comment]
Only like `[[Grunn, le roi solitaire lang:fr]]`.

**Comment by spirius44** [comment]
Thanks ;).


Cordialement,

Frédéric Modine

**Comment by spirius44** [comment]
[[foudre lang:fr]] don’t work :/.

Cordialement,

Frédéric Modine

**Comment by NilsEnevoldsen** [comment]
That's just because it matches multiple cards. The same error happens in English with `[[lightning]]`.

**Comment by spirius44** [comment]
Too bad :/. I hope your bot will be soon updated!


Cordialement,

Frédéric Modine

**Comment by bra1n** [comment]
Thanks for the new feature, @csuhta!
@spirius44 there are other MTG Discord bots that already support that. :wink:

**Comment by spirius44** [comment]
Beautiful! Thanks a lot! Can you tell me how obtain only full image of card with judge bot please?


Cordialement,

Frédéric Modine

**Comment by spirius44** [comment]
Moreover, there is no function (scryfall/judgebot) to automatically delete message with a user's bot command?

Cordialement,

Frédéric Modine
