### ISSUE TITLE
API Inconsistency: fuzzy search includes extras while regular search does not

### ISSUE THREAD

**Issue by bra1n** [scryfall/feedback#284]
Looking up The Cheese Stands Alone:
https://api.scryfall.com/cards/search?q=cheese - 0 results
https://api.scryfall.com/cards/named?fuzzy=cheese - 1 result

**Comment by csuhta** [comment]
This is intentional. `/cards/search` is designed to work (mostly) like the main site search. `/cards/named` is a fast lookup endpoint for chatbots, forums, and other similar software that need to fetch a single card by name.
