### ISSUE TITLE
Deck Builder's Toolkit lands missing from AKH

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#30]
The eight dual taplands that are in the Amonkhet Deck Builder's Toolkit but not in the Planeswalker Decks are not in Scryfall. They are numbers #279/269 to #287/269.

[Here are the ten.](https://scryfall.com/search?q=t%3Aland+%28e%3Asoi+or+e%3Aogw%29+r%3Au)

**Comment by csuhta** [comment]
@gmac Is this something you wanna add? 

Images are here: http://gatherer.wizards.com/Pages/Search/Default.aspx?sort=cn+&page=2&action=advanced&set=[%22Amonkhet%22]

**Comment by gmac** [comment]
Should be set. https://scryfall.com/search?q=%2B%2Be%3Aakh+t%3Aland&order=set
