### ISSUE TITLE
Question on rules for transform / split / flip cards

### ISSUE THREAD

**Issue by harryfino** [scryfall/feedback#311]
In the changelog announcement for May 1st, changes to transform / split / flip cards were announced: https://scryfall.com/changelog/notice-of-upcoming-changes-to-images-split-cards-and-flip-cards-46

When I search for Jace, Vryn's Prodigy, however, it doesn't return the `all_parts` field it used to. What is the current rules around transform / split / flip cards?

**Comment by csuhta** [comment]
Quick reply: That data is now in the `card_faces` object. We've combined transform cards into a single record like the previous change to split/flip cards.

https://api.scryfall.com/cards/ori/60?format=json&pretty=true

I'm tardy on writing a longer changelog post about this. Will update this ticket when there is more info.

**Comment by csuhta** [comment]
https://scryfall.com/changelog/api-recent-double-sided-card-and-image-updates-133
