### ISSUE TITLE
Incorrect colors on cards

### ISSUE THREAD

**Issue by card-collector** [scryfall/feedback#32]
The color and identity on some cards is wrong (seem to only be red and green, changed recently)
 - [ ] Crimson Kobolds (Legends, 139) - Expected color and identity: R
 - [ ] Crookshank Kobolds (Legends, 141) - Expected color and identity: R
 - [ ] Kobolds of Kher Keep (Legends, 157) - Expected color and identity: R
 - [ ] Wheel of Fate (Time Spiral, 187) - Expected color and identity: R
 - [ ] Hypergenesis (Time Spiral, 201) - Expected color and identity: G
 - [ ] Pact of the Titan (Future Sight, 103) - Expected color and identity: R
 - [ ] Summoner's Pact (Future Sight, 139) - Expected color and identity: G
 - [ ] Dryad Arbor (Future Sight, 174) - Expected color and identity: G
 - [ ] Crookshank Kobolds (Masters Edition, 090) - Expected color and identity: R
 - [ ] Crimson Kobolds (Masters Edition III, 093) - Expected color and identity: R
 - [ ] Kobolds of Kher Keep (Masters Edition III, 107) - Expected color and identity: R
 - [ ] Homicidal Brute (Innistrad, 047b) - Expected color and identity: R
 - [ ] Bane of Hanweir (Innistrad, 145b) - Expected color and identity: R
 - [ ] Wildblood Pack (Innistrad, 149b) - Expected color and identity: R
 - [ ] Terror of Kruin Pass (Innistrad, 152b) - Expected color and identity: R
 - [ ] Merciless Predator (Innistrad, 159b) - Expected color and identity: R
 - [ ] Rampaging Werewolf (Innistrad, 165b) - Expected color and identity: R
 - [ ] Ironfang (Innistrad, 168b) - Expected color and identity: R
 - [ ] Nightfall Predator (Innistrad, 176b) - Expected color: G
 - [ ] Nightfall Predator (Innistrad, 176b) - Expected identity: R, G
 - [ ] Garruk, the Veil-Cursed (Innistrad, 181b) - Expected colors and identity: B, G
 - [ ] Gatstaf Howler (Innistrad, 182b) - Expected color and identity: G
 - [ ] Krallenhorde Wantons (Innistrad, 185b) - Expected color and identity: G
 - [ ] Howlpack Alpha (Innistrad, 193b) - Expected color and identity: G
 - [ ] Ulvenwald Primordials (Innistrad, 208b) - Expected color and identity: G
 - [ ] Howlpack of Estwald (Innistrad, 209b) - Expected color and identity: G
 - [ ] Werewolf Ransacker (Dark Ascension, 081b) - Expected color and identity: R
 - [ ] Hinterland Scourge (Dark Ascension, 094b) - Expected color and identity: R
 - [ ] Tovolar's Magehunter (Dark Ascension, 098b) - Expected color and identity: R
 - [ ] Silverpelt Werewolf (Dark Ascension, 122b) - Expected color and identity: G
 - [ ] Moonscarred Werewolf (Dark Ascension, 125b) - Expected color and identity: G
 - [ ] Krallenhorde Killer (Dark Ascension, 133b) - Expected color and identity: G
 - [ ] Dryad Arbor (From the Vault: Realms, 005) - Expected color and identity: G
 - [ ] Summoner's Pact (Modern Masters, 164) - Expected color and identity: G
 - [ ] Chandra, Roaring Flame (Magic Origins, 135b) - Expected color and identity: R
 - [ ] Nissa, Sage Animist (Magic Origins, 189b) - Expected color and identity: G
 - [ ] Avacyn, the Purifier (Shadows over Innistrad, 005b) - Expected color and identity: R
 - [ ] Incited Rabble (Shadows over Innistrad, 046b) - Expected color and identity: R
 - [ ] Neck Breaker (Shadows over Innistrad, 147b) - Expected color and identity: R
 - [ ] Branded Howler (Shadows over Innistrad, 149b) - Expected color and identity: R
 - [ ] Gatstaf Ravagers (Shadows over Innistrad, 158b) - Expected color and identity: R
 - [ ] Vildin-Pack Alpha (Shadows over Innistrad, 159b) - Expected color and identity: R
 - [ ] Flameheart Werewolf (Shadows over Innistrad, 169b) - Expected color and identity: R
 - [ ] Skin Shedder (Shadows over Innistrad, 182b) - Expected color and identity: R
 - [ ] Moonrise Intruder (Shadows over Innistrad, 190b) - Expected color and identity: R
 - [ ] Ancient of the Equinox (Shadows over Innistrad, 194b) - Expected color and identity: G
 - [ ] Krallenhorde Howler (Shadows over Innistrad, 203b) - Expected color and identity: G
 - [ ] Lone Wolf of the Natterknolls (Shadows over Innistrad, 209b) - Expected color and identity: G
 - [ ] Timber Shredder (Shadows over Innistrad, 210b) - Expected color and identity: G
 - [ ] Lambholt Butcher (Shadows over Innistrad, 215b) - Expected color and identity: G
 - [ ] Werewolf of Ancient Hunger (Shadows over Innistrad, 225b) - Expected color and identity: G
 - [ ] One of the Pack (Shadows over Innistrad, 229b) - Expected color and identity: G
 - [ ] Ulrich, Uncontested Alpha (Eldritch Moon, 191b) - Expected color and identity: R, G
 - [ ] Wheel of Fate (Commander 2016, 138) - Expected color and identity: R
 - [ ] Tovolar's Magehunter (Launch Parties, 017b) - Expected color and identity: R
 - [ ] Howlpack Alpha (Prerelease Events, 051b) - Expected color and identity: G
 - [ ] Chandra, Roaring Flame (San Diego Comic-Con 2015, 135b) - Expected color and identity: R
 - [ ] Nissa, Sage Animist (San Diego Comic-Con 2015, 189b) - Expected color and identity: G

Unsure if the colors on the following card is correct, the card says it is colorless (similar to devoid, which do not have a color set) but it recently had a color set
 - [ ] Ghostfire (Future Sight, 115) - Expected colors none
 - [ ] Ghostfire (Duel Decks: Knights vs. Dragons, 069) - Expected colors none

I also noticed a lot of split and transform cards had their colors updated to only take into account the individual side.  I assumed that was an intentional change so I did not include them here.

**Comment by csuhta** [comment]
All of these should been fixed. Thank you again for the thorough report!
