### ISSUE TITLE
Any way to exclude prerelease cards?

### ISSUE THREAD

**Issue by harryfino** [scryfall/feedback#320]
In the last couple days, a lot of the spoiled cards have made their way into scryfall, but have consequently caused issues alongside other stable cards. Is there any way to exclude prerelease cards (or at least cards that do not have a valid multiverse id) from search?

Examples of cards causing issues for me: new basic lands, Thundermaw Hellkite, and Bogardan Hellkite. Any guidance is appreciated!

**Comment by harryfino** [comment]
I'm writing an application that depends on the card having a multiverse id. Since these cards don't have one, it's causing issues where the app thinks all of these cards are the same.

**Comment by silasary** [comment]
There are plenty of cards that don't have multiverse ids for valid reasons - Promos, rarities, gleemox...

You should probably just discard the relevant entries while sanitizing the data coming into your application.

**Comment by harryfino** [comment]
I think sanitizing is definitely something I should do. I'm not sure how I would get a complete set of data from the search API though (when I don't want to return all printings using `++`). If I did a search for t:Dragon -- only the last Thundermaw Hellkite would come back with no muiltiverse_id, so sanitizing would just eliminate it from the results entirely.

Maybe I should just be using the `id` field? I only went with `multiverse_id` because I know the rules of uniqueness and that they directly translate to Gatherer.

**Comment by csuhta** [comment]
I'm still a bit unclear on what you're trying to accomplish here.

- If you don't include `++` in your search query to unroll it, you will only receive one result per Oracle card name. Those kinds of searches are designed for deckbuilding or looking up cards by functionality. For those searches we try to return a good-looking and recognizable reprint for the cards in question.
- Not all cards have a `multiverse_id`. Gatherer only really has draftable and preconstructed products listed. They're missing all promos, most alternate foils, really esoteric sets, tokens, emblems, etc. 
- We have an endpoint for downloading the entire database: https://scryfall.com/docs/api-methods#method-all-cards You don't need to use the search system to download large swaths of cards. You can ignore any objects here that you don't want when you iterate.
- `multiverse_id` lets you reconcile card entries in our database with Gatherer pages, but they're not really useful beyond that. If you're downloading a copy of the Scryfall database, you should use the `id` column for unique storage concerns.

Does that help?

**Comment by harryfino** [comment]
Yes, this definitely helps. Thanks for taking the time to write this all up -- really appreciate what you guys are doing here.

Some background on me: I'm making a deck building application that doesn't need to consider emblems, tokens, promo cards, etc, and I'm also using the search API almost exclusively -- which is probably why I never ran into this situation until now. I was able to get things working temporarily by excluding Ixalan and Iconic Masters in my search queries, but I quickly released that my method of storing cards in a deck based on `multiverse_id` was flawed. I switched things over and now I'm back in action.

I'm not having any problems anymore, so I'm going to close this issue; however, I still think that having a search flag to exclude unreleased cards could be a good idea. If you guys want to discuss the value of something like that, feel free to reopen the issue.

Thanks again for the thoughtful replies and helping me navigate this situation! I'm loving the work you guys are doing!
