### ISSUE TITLE
Feature request: Show number of search hits on mobile site

### ISSUE THREAD

**Issue by gnyl** [scryfall/feedback#326]
I think your mobile site is great, but I very frequently find myself using the "request desktop site" feature on my phone because I want to see how many hits my search got, e.g. "how many blue instant and sorcery cards are currently legal in standard?"

**Mobile site.** Doesn't show the number of search hits, nor the number of pages, nor the number of cards per page. Not very useful.
![screenshot_20170910-144710](https://user-images.githubusercontent.com/25405901/30253373-445b6700-9638-11e7-9f8c-f19cc8ba66d2.jpg)

**Desktop site.** I highlighted in red the information I wish the mobile site would also show me.
![screenshot_20170910-144722](https://user-images.githubusercontent.com/25405901/30253374-445e8282-9638-11e7-8839-c3bbde8a09cd.jpg)

**Comment by doppeldeveloper** [comment]
I think this would be helpful as well. Usually on a phone I just take a look at whether or not the Next button is enabled to see whether there are "a lot" or "not many" because I can't find out more than that.

**Comment by josephprice** [comment]
Related tweet: https://twitter.com/RogueArtificer/status/912756206736781312

**Comment by csuhta** [comment]
The number of results and size of your page is now shown on mobile layouts https://scryfall.com/search?q=t%3Ainstant&unique=cards&as=grid&order=name
