### ISSUE TITLE
Specific cards with wrong frame

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#33]
- [x] https://scryfall.com/card/mpr/2
 - [ ] many of https://scryfall.com/search?order=set&q=e:ppre+frame:1993, but lack of images makes it harder
 - [x] https://scryfall.com/card/g11/6
 - [x] https://scryfall.com/card/f03/10
 - [x] https://scryfall.com/card/f03/11
 - [x] https://scryfall.com/card/f03/12
 - [x] https://scryfall.com/card/plpa/4
 - [x] https://scryfall.com/card/parl/52
 - [x] https://scryfall.com/card/parl/58
 - [x] https://scryfall.com/card/parl/59
 - [x] https://scryfall.com/card/parl/60
 - [x] https://scryfall.com/card/parl/72
 - [x] https://scryfall.com/card/parl/73
 - [x] https://scryfall.com/card/parl/74
 - [x] https://scryfall.com/card/parl/80
 - [x] https://scryfall.com/card/parl/81
 - [x] https://scryfall.com/card/parl/82
 - [x] https://scryfall.com/card/parl/83
 - [x] https://scryfall.com/card/psus/9
 - [x] https://scryfall.com/card/psus/12
 - [x] https://scryfall.com/card/psus/13
 - [x] https://scryfall.com/card/psus/15
 - [x] https://scryfall.com/card/psus/16
 - [x] https://scryfall.com/card/psus/17
 - [x] https://scryfall.com/card/psus/18

**Comment by gmac** [comment]
Any chance you could regenerate this list? Looks like I've moved some of those cards during the ongoing promo set archival work. That's for collecting all of these.

**Comment by NilsEnevoldsen** [comment]
@gmac Done

**Comment by gmac** [comment]
The missing PPRE images are a separate issue being tracked in https://github.com/scryfall/feedback/issues/34. Closing this specific list of card frame issues out as done.
