### ISSUE TITLE
Display format and sort order should be preserved between Advanced searches

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#331]
Display format and sort order are preserved between searches from the results page, but going to Advanced Search resets them.

**Comment by gmac** [comment]
We actually did this at one time – your sort and format prefs were cached in local storage and applied to all subsequent site search forms. Unfortunately, the general consensus was that for every time the feature was helpful, there was another time when it just felt weird.

**Comment by csuhta** [comment]
You can now choose your format using the controls in #330. Using the back button to go back to the form should maintain your choices.
