### ISSUE TITLE
Create a display format with rule text but no images

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#332]
Similar to mc.info's "spoiler" display format. It has the advantage of being fast to browse updated rule text, while not taking up as much room as "full". I imagine format legality and complete print information would also be omitted in this display format.

**Comment by NilsEnevoldsen** [comment]
A user has also pointed out that such a mode also has a small discretion benefit. Large images are very visible to over-the-shoulder peepers, and some users might care about that.

**Comment by NilsEnevoldsen** [comment]
#434 also brings up the benefit of such a display format for bandwidth-limited connections.

**Comment by csuhta** [comment]
There is now a text-only mode that shows Oracle information in a grid: https://scryfall.com/sets/ust?as=text
