### ISSUE TITLE
Allow sort by artist

### ISSUE THREAD

**Issue by chuckharmston** [scryfall/feedback#339]
There are some use cases for allowing a sort by artist, such as artist constructed players scanning new sets to see goodies.

Suggested by Erik Linden on Twitter here: https://twitter.com/ErikLinden/status/907437330889408512

**Comment by NilsEnevoldsen** [comment]
Another use case: sorting land cycles, e.g. https://scryfall.com/search?q=++t:basic+b:ala or https://scryfall.com/search?q=++t:basic+b:c16.

**Comment by csuhta** [comment]
:tada: https://scryfall.com/blog/feburary-2018-feature-update-153
