### ISSUE TITLE
Many promo card images are not loading

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#34]
In [e:ppre](https://scryfall.com/search?q=e:ppre), many card images are not loading.

Examples:
 - Abbott of Keral Keep, https://img.scryfall.com/cards/en/ppre/198.jpg returns the error below
 - Abhorrent Overloard, https://img.scryfall.com/cards/en/ppre/70.jpg works

```xml
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>0C6F89B320B7E457</RequestId>
<HostId>
ZsB13c9iXP9wFMwnZI1vhrpFFyfZSfzxg7aPuuBAznYHrbvoaOYF13xIjo+k30f25+3rNGwNqUc=
</HostId>
</Error>
```

**Comment by gmac** [comment]
I spoke with Corey about this one last week and those are broken because we currently don't have images for them.

**Comment by NilsEnevoldsen** [comment]
Maybe a Magic card back could be displayed in the place of missing images?

**Comment by gmac** [comment]
That's not a bad idea...

**Comment by gmac** [comment]
@NilsEnevoldsen – Corey also mentioned that promo images should all be available in the CCGHQ archives, though it is massive and woefully disorganized. Download links are here: https://gist.github.com/csuhta/a13bf90ddba7748d8f3f9a79b02add6e

I grabbed some of the Promo archive bundles, and it looks like those have all been added to Scryfall (ie: the low-hanging fruit has been picked). If you'd be interested in downloading the bundles and helping to dig through the back-40 for missing images, we'd greatly appreciate the help!

**Comment by csuhta** [comment]
@gmac I want to hold on this until we make the high-res image update. That way we don't have to do this manual work twice.

**Comment by gmac** [comment]
Many images in https://scryfall.com/search?order=set&q=e:ppre are not loading. High-resolution images of these cards should be available in CCGHQ image archives, but will require some digging through large file archives to find them. If anyone would like to help with tracking down these images, CCGHQ scan downloads are listed here: https://gist.github.com/csuhta/a13bf90ddba7748d8f3f9a79b02add6e

Dig away.

**Comment by csuhta** [comment]
There are no longer any cards on the site without images! https://scryfall.com/search?q=not%3Aimagedata 🎉

**Comment by NilsEnevoldsen** [comment]
Wow? Wow. Wow!
