### ISSUE TITLE
API: Return a URI to the set SVG image in set objects

### ISSUE THREAD

**Issue by csuhta** [scryfall/feedback#36]
https://twitter.com/dylansmithing/status/861369724948537344

**Comment by card-collector** [comment]
If you're looking for more stuff to include in the set API the block would be nice.  It is currently on the sets page but not returned with the API.

**Comment by csuhta** [comment]
@card-collector The `block` field is now available. Still working on the SVG one though.

**Comment by csuhta** [comment]
Set objects now include their SVG image, block, card count, and other new data. Please check it out!

- Doc: https://scryfall.com/docs/api-overview#type-set
- Ex: https://api.scryfall.com/sets/thou
