### ISSUE TITLE
Draft-Matters cards from Conspiracy/Conspiracy 2 don't have the wax seal watermark

### ISSUE THREAD

**Issue by silasary** [scryfall/feedback#386]
All [conspiracies](https://scryfall.com/search?q=t%3Aconsp) and [draft-matters](https://scryfall.com/search?q=o%3A%22as+you+draft%22+or+o%3A%22draft+%7E%22) cards from both conspiracy sets have a weird watermark.

This should be listed.

**Comment by csuhta** [comment]
Any opinions on what this should be called? 

- `wm:draft`?
- `wm:draftseal`?
- `wm:conspiracy`?
- Something else?

**Comment by silasary** [comment]
I think `wm:conspiracy ` is probably the best option

**Comment by doppeldeveloper** [comment]
I agree. :) It's the conspiracy wax seal.

**Comment by NilsEnevoldsen** [comment]
[WotC calls it a "crown watermark".](http://wpn.wizards.com/en/article/what-know-about-conspiracy-take-crown) Agree that `wm:conspiracy` seems right.

**Comment by csuhta** [comment]
Added! https://scryfall.com/search?q=wm%3Aconspiracy

Also there are a few aliases: `wm:seal` and `wm:draft`
