### ISSUE TITLE
Add aliases for the "planeswalker" watermark: "story" and "spotlight"

### ISSUE THREAD

**Issue by doppeldeveloper** [scryfall/feedback#397]
Currently all story spotlight cards are reachable by [searching `wm:planeswalker`](https://scryfall.com/search?q=wm%3Aplaneswalker), because the emblem depicted on them is the planeswalker symbol.

However, I still think of that as being *the story spotlight watermark,* and have recently tried to search `wm:story` and `wm:spotlight` as my first ports of call to figure out how to dredge those up. ([Neither of those watermark names returns results.](https://scryfall.com/search?q=wm%3Astory+or+wm%3Aspotlight)) I think these should be aliases for the same thing as `wm:planeswalker`.

This is similar mental logic behind why I search [`wm:orzhov`](https://scryfall.com/search?q=wm%3Aorzhov) and not `wm:sun`, and [`wm:boros`](https://scryfall.com/search?q=wm%3Aboros) and not `wm:fist`. They're named after not what the watermark symbol depicts but what the watermark *means* about the card's association: it's an Orzhov card, it's a Boros card, it's a Story Spotlight card.

**Comment by doppeldeveloper** [comment]
Btw, also, really happy you began gathering these together by watermark. :)

**Comment by csuhta** [comment]
This is now `wm:planeswalker` https://scryfall.com/search?q=wm%3Aplaneswalker

Also `wm:story` and `wm:storyspotlight` work too
