### ISSUE TITLE
is:storageland has strange inclusion criteria

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#406]
#51 added support for [is:storageland](https://scryfall.com/search?q=is:storageland), which is great. I'm a bit puzzled by the inclusion criteria, though. Right now it's Crucible of the Spirit Dragon plus the Time Spiral cycle. If Crucible is included, you might consider also adding [other storage lands](https://scryfall.com/search?q=o%3A%22storage+counter%22+not%3Areprint&order=set):
* Mage-Ring Network
* Masques cycle
* Fallen Empires cycle
* City of Shadows

**Comment by csuhta** [comment]
The criteria for this was, roughly, "the" storage lands. i.e. the cycle + 2 others that Commander players (ab)use.
