### ISSUE TITLE
The legendary transform lands from XLN do not show their color indicators

### ISSUE THREAD

**Issue by silasary** [scryfall/feedback#419]
https://scryfall.com/search?q=e%3Axln+is%3ATransform+t%3Alegendary

These lands are coloured (as evidenced by the tinted lines on the map, and the more traditional colour indicator on the MTGO renders), but they are listed as colorless in your db

**Comment by csuhta** [comment]
Do the lands have color indicators on MTGO? Can you provide a screenshot?

That seems like a mistake because [the Gatherer pages](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=435346) don't have a color indicator listed and no rulings or set release notes mention it.

While the lands are transformed, they have the converted mana cost of their front side, but not the mana cost or colors (rule 202.3b). So unless ability text or an Oracle color indicator gives them colors, they are colorless.

**Comment by silasary** [comment]
Here's one I saw on Twitter.

https://twitter.com/MishrasFotoshop/status/912718808141500416

I'll get some screenshots myself when I get in front of my computer

**Comment by silasary** [comment]
Hmm.  I think I need to do more investigation.  Despite looking very green, the card does not actually have a color indicator circle.
![image](https://user-images.githubusercontent.com/194254/30899101-deda43fc-a3a1-11e7-9a3c-b8ac6fe0e7a3.png)

Reaching out to Eli over twitter.

**Comment by doppeldeveloper** [comment]
There's no color indicator line on gatherer, e.g. compare [Itlimoc](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=435347) vs [Homicidal Brute](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=221185)'s "Color Indicator: Red" line. The cards being tinged a color (despite not *being* that color) strikes me as being like how they color lands: Forests are tinged green but not green; multicolor lands have a hybrid appearance or a gold appearance despite having no colors themselves. It's a design communication thing so you usually don't have to read the text to know what colors the card adds.

My guess would be the [Mirsha's Photoshop preview you linked](https://twitter.com/MishrasFotoshop/status/912718808141500416) was an in-development version where the color indicator was a bug. I'd be interested to see what WOTC have to say.

**Comment by silasary** [comment]
Official Ruling: [They are colorless](https://twitter.com/EliShffrn/status/913034737450708992)

**Comment by gmac** [comment]
That green frame is a pretty confusing design choice.

**Comment by csuhta** [comment]
MTGO strikes again. Thanks for looking into this! 

![giphy](https://user-images.githubusercontent.com/769083/30939570-dc86cd0a-a3ab-11e7-8362-de505ca96167.gif)
