### ISSUE TITLE
Link to back face of a transform card

### ISSUE THREAD

**Issue by doppeldeveloper** [scryfall/feedback#421]
I'd like to be able to link to the back face of a transform card such that the image of the back face is the first one that shows, e.g. [Infectious Curse](https://scryfall.com/card/soi/97) specifically instead of Accursed Witch.

I suggest something like linking to `/card/soi/97b` might be workable, and the page loads card `97` and presents the back face.

We used to have this before the transform presentation update, and this update is beautiful. This would be convenient to still have available though.

**Comment by gmac** [comment]
Interesting thought. Sure, we could probably get something like this set up.

**Comment by gmac** [comment]
You got it. https://scryfall.com/card/xln/250?back

**Comment by doppeldeveloper** [comment]
Woohoo!

I like the way you implemented it, flipping over to the back face just after page loads makes it really clear it's the back face we're being shown. :)
