### ISSUE TITLE
Provide meta-information on searches

### ISSUE THREAD

**Issue by spacemonaut** [scryfall/feedback#422]
Right now I'm assessing making a Morph- and Manifest-based commander deck, using cards printed (or reprinted) since approx. 2014 since those are the ones I'm likely to already possess. I would love to be able to access amalgamated meta-information about the search results, such as:

* which colors (or color identities) feature in this search, in what proportions? ([MTG Wiki provides some information about this](https://mtg.gamepedia.com/Morph), but I don't know how it adds up once I eliminate cards from before 2014.)
* what powers/toughnesses do creatures in this search have?
* how many of each type show up? (e.g. how many Manifest creatures are there vs Manifest spells?)
* what are their mana costs?

I can gather this information by running many different searches, which I did -- I've figured out [Sidar Kondo](https://scryfall.com/card/c16/42) (GW) should be combined with another Partner with at least Blue in their color identity, since Blue has far more Morph cards than any other color. I've also figured out about half of them have power 2 or less, so Sidar Kondo will still be helpful for a large number of Morph cards even after they unmorph.

I think it would be beneficial if Scryfall could make available a way to get meta-information like this about specific queries, such as via a column graphs showing e.g. the five colors plus colorless and how many cards match that color, the min-max range of power and toughness found in the search and how many creatures correspond to each of those, etc.

**Comment by NilsEnevoldsen** [comment]
It would be good to see meta-information in the deckbuilder, so the same tech might be applied to queries and sets.

**Comment by gmac** [comment]
Interesting ideas, but these are fundamentally different takes on the data than what Scryfall search is optimized for, and are specific enough that they don't seem like a good fit for our API. However, we love seeing what developers do with our data. This sounds like a good case to build your own API that proxies the Scryfall API; it could pull down the data your need from us, analyze it, then return it with all the meta data you're after.
