### ISSUE TITLE
Conspiracy and Non-Standard Set Planeswalkers Showing as Reprints

### ISSUE THREAD

**Issue by josephprice** [scryfall/feedback#43]
Sample planeswalkers that seem like they're reprints:
https://scryfall.com/card/cn2/74
https://scryfall.com/card/cns/42
https://scryfall.com/card/cn2/75
https://scryfall.com/card/c14/10 (and all other planeswalkers)

Might be others... Is there a systematic issue?

**Comment by csuhta** [comment]
Nahiri is not incorrectly marked as a reprint, did you pick out the right version? https://scryfall.com/search?q=nahiri+not%3Areprint

The commander planeswalkers are due to Conspiracy sets not being marked as a first-print source, will fix.

**Comment by josephprice** [comment]
Yes, looks like I got C14 and reprints wrong!

**Comment by csuhta** [comment]
Conspiracy cards are fixed now, they are correctly identified as a reprint source https://scryfall.com/search?q=e%3Acn2+not%3Areprint
