### ISSUE TITLE
Various cards erroneously "legal" for 1v1 Commander

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#44]
I think all cards never printed in MTGO should be "not legal", such as Great Wall.

[Notably, the following cards on the Vintage banlist are currently "legal" for 1v1 Commander:](https://scryfall.com/search?q=-f%3Avintage+f%3A1v1)
 - [x] Conspiracies
 - [x] Ante cards
 - [x] Dexterity cards
 - [x] Shahrazad

I think they should be "not legal" by the criterion above, but otherwise they should be "banned".

**Comment by csuhta** [comment]
Fixed!
