### ISSUE TITLE
Alias == to =

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#45]
Programmers might instinctually use `==` instead of `=` as a comparison operator. I propose that syntax should be acceptable.

https://scryfall.com/search?q=cmc==12

**Comment by gmac** [comment]
I knew you were a programmer, Nils... that said, I don't fully agree with compromising syntax as an alternative for a select audience. I'd give this a 👎 .

Punting this over to Corey to make the final call.

**Comment by NilsEnevoldsen** [comment]
In what way is this compromising syntax? It's not that different from aliasing `e:` and `s:`.

**Comment by csuhta** [comment]
Done! https://scryfall.com/search?q=pow%3D%3D2

Also we aliased `:` to `=` also. It's all interchangeable now: https://scryfall.com/search?q=c%3Dred+pow%3A2
