### ISSUE TITLE
API Request: Provide matching face for searches

### ISSUE THREAD

**Issue by silasary** [scryfall/feedback#453]
For example: The search [re:"attacking creatures you control get +\w/+0 and"](https://api.scryfall.com/cards/search?q=re%3A%22attacking+creatures+you+control+get+%2B\w%2F%2B0+and%22&pretty=true) returns two cards, Breakneck Rider // Neck Breaker and Gruul War Chant.

It is not currently possible to know which side of that card is the one that I care about, unless I re-run the search parameters locally across each face of each DFC in the results.

**Comment by csuhta** [comment]
We've discussed this internally, and it's not something we can do without a ton of pain.

Your search on Scryfall is ultimately transformed into a SQL statement for Postgres, and Postgres does not provide signals about which part of a query matched a row, just if the row matches or not. 

There are hack-y ways to work around this, but all of them involve a performance tradeoff or re-implementing search features outside of Postgres.
