### ISSUE TITLE
Broken link in color improvements news post

### ISSUE THREAD

**Issue by doppeldeveloper** [scryfall/feedback#454]
https://scryfall.com/changelog/improvements-to-color-color-identity-operators-138

The `identity<=artifice` link points to the following link which doesn't work in my browser: 

https://scryfall.fwd.wf/search?q=identity%3C%3Dartifice&order=edhrec

!["tunnel not found" error page](https://user-images.githubusercontent.com/4585677/31276744-4a80660a-aa95-11e7-96da-42652ed8d706.png)

This update is pretty awesome. Thanks, Scryfall team. 🙂 💕

**Comment by chuckharmston** [comment]
Fixed! Thanks for the heads-up.
