### ISSUE TITLE
Emrakul, the Promised End doesn't show with identity filter

### ISSUE THREAD

**Issue by harryfino** [scryfall/feedback#457]
When searching for cards with a specific commander identity, Emrakul, the Promised End does not show up in the search results. Should this be filtered out of the results as it is today?

An example search query: https://scryfall.com/search?q=Emrakul+and+f%3ACommander+and+id%3AGRW+and+-e%3Aima

**Comment by doppeldeveloper** [comment]
This shows up if we use `id<=GRW`. Perhaps the `:` operators should be bound to their old behaviour for color (`>=`) and color identity (`<=`) for backward compatibility and common usage? Those were pretty intuitive bindings, but edge cases around greater than / less than / exactly equal were missing.

**Comment by csuhta** [comment]
The color identity operator was updated today. You now want to use `<=` here:

- https://scryfall.com/search?q=emrakul+t%3Alegendary+id%3C%3DGRW
- https://scryfall.com/changelog/improvements-to-color-color-identity-operators-138
