### ISSUE TITLE
Negating price keywords doesn't work

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#46]
> All keywords except for `include` can be negated by prefixing them with a hyphen (`-`). This inverts the meaning of the keyword to reject cards that matched what you’ve searched for.

This doesn't seem to work with price keywords.

Compare:
* https://scryfall.com/search?q=t:legendary+t:dragon (40 cards)
* https://scryfall.com/search?q=t:legendary+t:dragon+tix<=1 (35 cards)
* https://scryfall.com/search?q=t:legendary+t:dragon+tix>=1 (5 cards)
* https://scryfall.com/search?q=t:legendary+t:dragon+-tix<=1 (40 cards)
* https://scryfall.com/search?q=t:legendary+t:dragon+-tix>=1 (40 cards)

**Comment by csuhta** [comment]
The numeric comparators can't be `-` inverted, they aren't "keywords". Keywords are items with a colon like `o:` etc.

We've revised this section of the docs like 3 times and it's still confusing though, should rephrase.

**Comment by NilsEnevoldsen** [comment]
This did not occur to me. I suppose usually one would just change the comparator. I was trying to be clever and search for cards without a TIX price, but I suppose I will have to be cleverer.

**Comment by csuhta** [comment]
Yeah, you can just "invert" `tix<5` with `tix>=5`, etc

**Comment by gmac** [comment]
Sounds like the original report here has been sufficiently addressed. Closing this out.
