### ISSUE TITLE
Search by types of sets

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#471]
A print-level characteristic for the type of set the print is from. There is some conceptual overlap with `block:` syntax and `is:funny`, `is:promo`, `is:digital`, `is:masterpiece` etc.

The two types I _really_ want are just these:

* Expansion set (including so-called "standalone" sets)
* Core set

But of course there are zillions of others to consider, like:

* Portal/Starter set
* Theme deck
  - Duel deck
* Planeswalker deck
* Supplemental set
  - Vanguard set
  - Conspiracy set
  - Archenemy set
  - Commander set
  - Planechase set
  - Un-sets
* Commemorative set
* Compilation set
  - Masters set
  - Masterpiece set

The 80/20 solution might be to create `is:core` and `is:expansion` and call it a day.

**Comment by Sniffnoy** [comment]
It's probably worth noting that Scryfall already *has* a notion of types of sets; perhaps searching needs to be added, but classifying sets, at least, is something that's already been done.  (Although as I've pointed out elsewhere here, there is a problem that it seems like at the moment sets can only have one type, and some of them really need to have more than that.)

**Comment by silasary** [comment]
See conversation in #372

**Comment by NilsEnevoldsen** [comment]
Wow. I did not know `set_type` [already existed](https://scryfall.com/docs/api/sets). That's great.

**Comment by gmac** [comment]
There's also the handy pulldown on the sets page:

![screen shot 2017-10-11 at 2 42 42 pm](https://user-images.githubusercontent.com/727224/31459928-b4c6e560-ae92-11e7-86e2-7ac24125ac21.png)

**Comment by jhallbachner** [comment]
`st:core` and `st:expansion`, along with a host of other options, is now available: https://scryfall.com/docs/reference#sets
