### ISSUE TITLE
Request: `has:diacritic`

### ISSUE THREAD

**Issue by silasary** [scryfall/feedback#477]
These cards are incredibly frustrating, and it'd be nice to search them all at once.

**Comment by doppeldeveloper** [comment]
What makes them frustrating? As far as I can tell Scryfall does its best to strip diacritics, e.g. [`ring of maruf`] finds the punctuated-and-diacritic-ified Ring of Ma'rûf.

**Comment by csuhta** [comment]
Is this close enough? I just realized you could solve this with the new `name` regex. https://scryfall.com/search?as=&q=name%3A%2F%28à%7Cá%7Câ%7Cé%7C%C3%AD%7Cö%7Cú%7Cû%29%2F

**Comment by silasary** [comment]
Works for me 😄
