### ISSUE TITLE
EDHRec links for split / aftermath cards give 404

### ISSUE THREAD

**Issue by torbenbarsballe** [scryfall/feedback#479]
EDHRec links for split / aftermath cards give a 404 error.

For example, https://scryfall.com/card/akh/210 links to http://edhrec.com/route/?cc=Dusk+%2F%2F+Dawn

This seems to in part be an issue with the EDHRec route / query engine. Direct link ( e.g. https://edhrec.com/cards/dusk-dawn ) works fine.

**Comment by NilsEnevoldsen** [comment]
Fixed?

**Comment by csuhta** [comment]
Yep!
