### ISSUE TITLE
Flavor text of Magical Hacker is missing brackets

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#48]
https://scryfall.com/card/unh/37

Wrong:

> 1|= y()u (4|\\| r3@d 7#5, y0|_| /\r3 @ IVI0/\\/$+3|2 &33|

Right:

> 1|= y()u (4|\\| r3@d 7#][5, y0|_| /\r3 @ IVI0/\\/$+3|2 &33|<

**Comment by csuhta** [comment]
Fixed!

**Comment by NilsEnevoldsen** [comment]
You added, the square brackets, but you removed backslashes, and failed to add the left angle bracket. 😛

**Comment by NilsEnevoldsen** [comment]
I should add that getting the flavor text on Magical Hacker correct is a Priority 1 bug with large geopolitical implications, and you should probably just take Scryfall offline until it's fixed.
