### ISSUE TITLE
Link to tokens made by card on card page

### ISSUE THREAD

**Issue by Subbarker** [scryfall/feedback#492]
For instance, on the page for [Legion's Landing](https://scryfall.com/card/xln/22), link to [the vampire token from Ixalan ](https://scryfall.com/card/txln/1)

**Comment by Subbarker** [comment]
It seems like this is intended looking at the section: "FACES, TOKENS, & OTHER PARTS" on [some cards](https://scryfall.com/card/emn/15a).

**Comment by csuhta** [comment]
Duplicate of #203
