### ISSUE TITLE
Amonkhet Image Updates

### ISSUE THREAD

**Issue by josephprice** [scryfall/feedback#5]
From user feedback:
Prepare and Fight (both 220a and 220b) have the Italian spoiler image when Wizards' visual spoiler has the English image here: http://media.wizards.com/2017/dw466ytu5_akh/en_r7mhbh5b7d.png

Wizards' visual spoiler has the English image of Kefnet the Mindful here: http://media.wizards.com/2017/dw466ytu5_akh/en_6DoXr2pipg.png

Wizards' visual spoiler has the English image for this card, which is actually named Lay Bare the Heart: http://media.wizards.com/2017/dw466ytu5_akh/en_jM6FNsgWFJ.png

**Comment by csuhta** [comment]
Updated https://scryfall.com/search?q=%28lay+bare+heart%29+or+%28kefnet+mindful%29+or+%28%21prepared%29
