### ISSUE TITLE
Bind the : operator for color & color identity to its old meaning

### ISSUE THREAD

**Issue by spacemonaut** [scryfall/feedback#502]
Searching `c:mardu` and `id:mardu` used to be equivalent to `c>=mardu` and `id<=mardu`, though nowadays `:` is aliased to `=` in these cases, an exact match.

The new color operator update is sincerely fantastic and I'm glad we have it, since it's greatly improved my ability to run searches which previously were difficult to intuit or would have required excessive writing. The color nicknames like "mardu" are also wonderful.

However, I think `c:` and `id:` should still function as `c>=` and `id<=` like before: these remain the primary use case for color and color identity search cases, and the original behaviour was well-chosen. Such an aliasing maintains backwards compatibility (as someone ran into in #457) and cross-compatibility search engines like Magiccards.info. Nowadays I often initially type `c:stuff` or `id:stuff`, and I either search and think for a moment why I'm not getting the results I expected, or I catch myself as I write out my query and revise it to `c>=stuff` or `id<=stuff` -- I'm getting better at catching myself sooner or remembering outright though.

I representing this intuitive and primary use case in an easier-to-type shortcut of `:` would be a positive thing for Scryfall's search service and maintain it as an intuitive tool.

**Comment by silasary** [comment]
Yeah, I'm also in favor of keeping `:` as backwards compatible with the old scheme (and other engines)

**Comment by csuhta** [comment]
We've reverted this operator https://scryfall.com/blog/feburary-2018-feature-update-153
