### ISSUE TITLE
Add shortcuts for other land cycles (or deprecate that feature)

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#51]
> You can find some interesting land groups with is:bounceland, is:gainland, is:fastland, is:checkland, is:shockland, is:fetchland, is:filterland, and is:dual

Some other common cycles:

- [ ] painland - Adarkar Wastes
- [ ] storageland - Calciform Pools
- [ ] battleland/tangloland- Prairie Stream
- [ ] cycleland - Irrigated Farmland
- [ ] shadowland - Port Town
- [ ] scryland - Temple of Enlightenment
- [x] gainland - add Sejiri Refuge and other ZEN gainlands
- [ ] manland - Celestial Colonnade and everything that matches `o:"It’s still a land." t:land`

Keeping up with all of these is a chore, and part of me is sympathetic to just dropping them entirely, or making them undocumented. But if you want to advertise keywords like `is:checkland`, you should probably add the other common ones.

**Comment by csuhta** [comment]
We have added:

[bikeland](https://scryfall.com/search?q=is:bikeland) (Alias `cycleland` and `bicycleland`
[bounceland](https://scryfall.com/search?q=is:bounceland) (Alias `karoo`)
[checkland](https://scryfall.com/search?q=is:checkland)
[dual](https://scryfall.com/search?q=is:dual)
[fastland](https://scryfall.com/search?q=is:fastland)
[fetchland](https://scryfall.com/search?q=is:fetchland)
[filterland](https://scryfall.com/search?q=is:filterland)
[gainland](https://scryfall.com/search?q=is:gainland)
[painland](https://scryfall.com/search?q=is:painland)
[scryland](https://scryfall.com/search?q=is:scryland)
[shadowland](https://scryfall.com/search?q=is:shadowland)
[shockland](https://scryfall.com/search?q=is:shockland)
[storageland](https://scryfall.com/search?q=is:storageland)
[tangoland](https://scryfall.com/search?q=is:tangoland) (Alias `battleland`)

**Comment by silasary** [comment]
How about [is:triland](https://scryfall.com/search?q=re%3A%22%5E%7BT%7D%3A+Add+%7B%5Cw%7D%2C+%7B%5Cw%7D%2C+or+%7B%5Cw%7D%22+t%3Aland+-t%3Alair)?
