### ISSUE TITLE
Scryfall discord bot results mana symbols don't work in Android

### ISSUE THREAD

**Issue by doppeldeveloper** [scryfall/feedback#523]
This is one of those cases where an image will be clearer than explaining it:

![screenshot_20171025-163014_01](https://user-images.githubusercontent.com/4585677/32007752-5ae53fc2-b9a2-11e7-976e-cfdf30b78c9d.jpg)

**Comment by silasary** [comment]
This is a bug with Discord, and not something that Scryfall (or any other bot) can do anything about.
