### ISSUE TITLE
List of paper promos with incorrect frames

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#538]
https://scryfall.com/search?q=%2B%2Bframe%3A1993+year%3E1997+game%3Apaper+-e%3Aprm

Every card in that list is either frame:1997 or frame:2003.

**Comment by csuhta** [comment]
@jhallbachner Could you adjust these and also set the correct image crop for each? It seems to varied to apply it with SQL

**Comment by jhallbachner** [comment]
These are all fixed now.
