### ISSUE TITLE
BFZ basics images are misnumbered

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#55]
https://scryfall.com/search?q=%2B%2B+t:basic+e:bfz&order=set

Looks like the full-art lands screwed up card numbers.

**Comment by csuhta** [comment]
Fixed:

- https://scryfall.com/search?q=%2B%2Be%3Abfz%20t%3Abasic&order=set
- https://scryfall.com/search?q=%2B%2Be%3Aogw+t%3Abasic&order=set
