### ISSUE TITLE
Incorrect symbol on funny planeswalkers

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#555]
The funny planeswalkers have `-` (hyphen-minus) abilities instead of `−` (minus) abilities.

https://scryfall.com/card/htr/1
https://scryfall.com/card/htr/2

I noticed this with the search [https://scryfall.com/search?q=o:"-2:"](https://scryfall.com/search?q=o:"-2:"). It's worth thinking about what that search should return.

**Comment by doppeldeveloper** [comment]
I didn't even know there were separate minus characters being used!

Checking through results there's -X/-X effects, levellers (e.g. [brimstone mage](https://scryfall.com/card/roe/137)) which say "level 1-2", and planeswalkers. If they all use the same minus character I can still pry those apart by regex or just excluding planeswalkers or levellers depending on what I'm looking for.

**Comment by csuhta** [comment]
Fixed!
