### ISSUE TITLE
Rename MPR to P02

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#58]
https://scryfall.com/search?q=e:mpr

Looks like all the MPR cards are now PXX, except 2002 MPR. (Wasteland was also a 2001 MPR.)

**Comment by csuhta** [comment]
This is going to stay as-is for now, so people can find the "MPR" collection they might have seen on other sites.

It (very) loosely follows the convention of other first-time set codes and their follow ups:

```
CNS
CN2

CMD
C13
C14

MPR
P03
P04
```

etc

**Comment by NilsEnevoldsen** [comment]
I did not realize this. Thanks.
