### ISSUE TITLE
Anthologies appears as an Expansion for the purposes of `st:`

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#583]
Despite https://api.scryfall.com/sets/ath reporting that _Anthologies_ is `"set_type": "box"`, _Anthologies_ cards show up in [++!"giant growth" st:expansion](https://scryfall.com/search?q=%2B%2B%21%22giant+growth%22+st%3Aexpansion) but not [++!"giant growth" st:box](https://scryfall.com/search?q=%2B%2B!%22giant+growth%22+st%3Abox).

**Comment by NilsEnevoldsen** [comment]
Also CEI and CED show up as both core and box. Should just be box.

**Comment by jhallbachner** [comment]
Fixed these tags with Anthologies.

I had the Collectors' Editions as Coresets since they're just direct equivalents to Beta edition, but open another issue for that specifically if you think that's an incorrect call.
