### ISSUE TITLE
CED/CEI appear as Core sets for the purposes of `st:`

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#584]
CED and CEI are box sets. The important distinction is that box sets come with a predetermined selection of cards.

**Comment by chuckharmston** [comment]
I suspect that they should actually be `memorabilia`, since they're not playable. @jhallbachner?

**Comment by jhallbachner** [comment]
Actually made this change already, e.g. https://scryfall.com/search?q=lotus+%28+%28e%3Aced+and+st%3Acore%29+or+%28e%3Acei+and+st%3Amemorabilia%29+%29
