### ISSUE TITLE
Add block constructed legalities

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#587]
https://magic.wizards.com/en/game-info/gameplay/rules-and-formats/banned-restricted

Block play requires a Constructed deck, which must contain a minimum of sixty cards. All cards in your deck must be from a single block of Magic releases.

The following cards are banned in block-constructed tournaments:

Intangible Virtue (Innistrad-Avacyn Restored block)
Lingering Souls (Innistrad-Avacyn Restored block)
AEther Vial (Mirrodin block)
Ancient Den (Mirrodin block)
Arcbound Ravager (Mirrodin block)
Darksteel Citadel (Mirrodin block)
Disciple of the Vault (Mirrodin block)
Great Furnace (Mirrodin block)
Seat of the Synod (Mirrodin block)
Tree of Tales (Mirrodin block)
Vault of Whispers (Mirrodin block)
Skullclamp (Mirrodin block)
Lin Sivvi, Defiant Hero (Masques block)
Rishadan Port (Masques block)
Gaea's Cradle (Urza block)
Memory Jar (Urza block)
Serra's Sanctum (Urza block)
Time Spiral (Urza block)
Tolarian Academy (Urza block)
Voltaic Key (Urza block)
Windfall (Urza block)
Cursed Scroll (Tempest block)
Squandered Resources (Mirage block)
Amulet of Quoz (Ice Age Block)
Thawing Glaciers (Ice Age block)
Zuran Orb (Ice Age block)

**Comment by chuckharmston** [comment]
As it's not a currently-supported format, it isn't likely that we will support it. [`is:spikey`](https://scryfall.com/search?q=is%3Aspikey) may have what you're looking for, though?
