### ISSUE TITLE
Related Cards not shown in JSON data

### ISSUE THREAD

**Issue by TrophyBuck** [scryfall/feedback#591]
Bottom of page here mentions tokens & related cards should be in a section of the JSON data, but I'm not seeing it when going through the JSON.

API:
https://scryfall.com/docs/api/cards in Related Cards section

Ex:
https://api.scryfall.com/cards/named?exact=beast+within doesn't have a "related cards" section with the beast token.

Thanks!

**Comment by csuhta** [comment]
Not all token producers have related cards assigned, we haven't yet assigned generic tokens to cards. Only very specific tokens or named cards are coupled together.

Here's an example of a cards that do:

- https://scryfall.com/search?q=is%3Ameld
- https://scryfall.com/card/hou/161
- https://api.scryfall.com/cards/hou/161?format=json&pretty=true
