### ISSUE TITLE
APAC set is missing (or typo in code)

### ISSUE THREAD

**Issue by JayDi85** [scryfall/feedback#593]
That APAC set is missing from database at all:

[Asia Pacific Land Program](http://mtg.wtf/set/apac)

**Comment by JayDi85** [comment]
Hmm, but I found [PALP](https://scryfall.com/sets/palp) instead. Have you a typo in set's code?

**Comment by csuhta** [comment]
Neither `APAC` or `PALP` is the set code for these lands, both sites are using an unofficial code. Our code is `PALP`
