### ISSUE TITLE
Arena League 1996 (PARL) have type in set's code?

### ISSUE THREAD

**Issue by JayDi85** [scryfall/feedback#594]
[Arena League 1996](https://scryfall.com/sets/parl) set's have code is PARL, but all other years have "year code" like [PAL99](https://scryfall.com/sets/pal99), PAL00, PAL01.

Are there type in code?

**Comment by csuhta** [comment]
This roughly follows how the codes for some official sets work:

- Conspiracy — CNS
- Conspiracy: Take the Crown — CN2
- Commander 2011 — CMD
- Commander 2012 — C12
- Commander 2013 — C13

Again, we're just making up set codes for unofficial promo sets
