### ISSUE TITLE
Problem with Urza's Science Fair Project (UGL)

### ISSUE THREAD

**Issue by card-collector** [scryfall/feedback#64]
https://scryfall.com/card/ugl/83

The "o2" text should be "{2}".

Side note: The auto-fill for the feedback form is populating with Skirk Commando rather than what was passed in from the URL and when I attempted to submit using the feedback form I received an error (HTTP/1.1 422 Unprocessable Entity).  I don't know if it is related to my browser settings or not.

**Comment by chuckharmston** [comment]
Fixed! Thanks for the report.

cc @gmac for the info about the form ^
