### ISSUE TITLE
Remove pipes from host creature names

### ISSUE THREAD

**Issue by doppeldeveloper** [scryfall/feedback#653]
@Sniffnoy noticed this one -- Host creatures [don't have pipes in their names on Gatherer](http://gatherer.wizards.com/Pages/Search/Default.aspx?type=+[Host]), i.e. Ordinary Pony just has an ordinary name of "Ordinary Pony".

[Scryfall adds pipes to these names](https://scryfall.com/search?as=full&q=t%3Ahost) but should probably go with the Gatherer naming non-convention.

**Comment by silasary** [comment]
Note that having pipes in card names is causing issues wherever we use | as a delimiter.

**Comment by csuhta** [comment]
Fixed
