### ISSUE TITLE
Colors and Color Identity example "color>=uw -c:red" doesn't filter out red cards.

### ISSUE THREAD

**Issue by foilking** [scryfall/feedback#655]
I found that the example query "color>=uw -c:red" doesn't filter out cards that have red in their casting cost. Example:
![screen shot 2017-11-30 at 4 29 00 pm](https://user-images.githubusercontent.com/2407118/33458397-9d1bb7b2-d5eb-11e7-8dc4-007bcb6d2c18.png)
Atogatog shouldn't be in this list. This is true for the API also.

**Comment by Sniffnoy** [comment]
I think this is because c:red is being interpreted as c=r, rather than c>=r.  I think this is already covered by #502, which asks for c:red to be interpreted as c>=r.

**Comment by foilking** [comment]
Good call! I tested both = and >=. The first game me the result I was getting, the second is the result I was expecting. The references page should be updated.

**Comment by csuhta** [comment]
This has been fixed
