### ISSUE TITLE
Feature request: Be able to search for tombstone symbol?

### ISSUE THREAD

**Issue by Sniffnoy** [scryfall/feedback#662]
I just realized there's not any way to search for cards (or rather printings -- makes more sense as a printing-level thing) with the tombstone symbol.  Any chance this could be added?  Thank you!

**Comment by gmac** [comment]
Good call! https://scryfall.com/search?q=is%3Atombstone

**Comment by silasary** [comment]
Crippling Fatigue promo is missing from the query:  https://scryfall.com/card/phuk/6

**Comment by gmac** [comment]
Good catch. That wasn't included in the list on the MtG wiki page I was
going from.
