### ISSUE TITLE
Request: last update timestamp in API

### ISSUE THREAD

**Issue by gwax** [scryfall/feedback#663]
I would like to cache API responses from Scryfall until data changes but, without making a new request, there is currently no way to tell when something was last updated/changed.

It would be great is bulk API responses (specifically `/cards` and `/sets`) included a field indicating last gameplay data update. This could be a version number, an iso8601 datetime, etc.

Then, if there were a separate endpoint for metadata (`/metadata` or the like) that provided just the last update information, I could make a request for `/metadata`, see that the current version matches the version in my cache and forego making any other requests.

This would be great for me because it saves me from waiting while I re-download everything and it would be great for you because you'll have to serve fewer responses and less data.

**Comment by Gonkers** [comment]
Typically you would use an `If-Modified-Since` header int the GET request while calling the same API endpoint. You would then only get the records that have been "modified since" the date you provided.  
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since

**Comment by gwax** [comment]
Scryfall's API endpoints do not respond with `Last-Modified` headers so `If-Modified-Since` isn't really an option.

Ultimately, I've managed to solve my problem by pulling the Changelog feed, storing the Etag value and using `If-None-Match` to check for changes.

**Comment by Gonkers** [comment]
Good to know, thanks for the follow up.
