### ISSUE TITLE
Starter 2000: wrong images

### ISSUE THREAD

**Issue by JayDi85** [scryfall/feedback#664]
[Starter 2000 set](https://scryfall.com/sets/s00) have wrong images?

As example [Ogre Warrior](https://scryfall.com/card/s00/33) -- it's haven't rarity icon like other. And there are many same cards:

![shot_171220_002832](https://user-images.githubusercontent.com/8344157/34177337-bcad6536-e51c-11e7-9f94-c3b3caa06331.png)

**Comment by csuhta** [comment]
Starter 2000 contained cards reprinted from Sixth Edition, Starter 1999, and Portal. The cards from Sixth Edition are identical. The ones from Portal and Starter have no expansion symbol. 

https://mtg.gamepedia.com/Starter_2000
