### ISSUE TITLE
API: missing cards from search by set request

### ISSUE THREAD

**Issue by JayDi85** [scryfall/feedback#665]
If you request set's data by search API: [search?q=++e:leb](https://api.scryfall.com/cards/search?q=++e:leb) then it not return all data:
 - 1. [search by website](https://scryfall.com/sets/leb) return 302 cards (3 forests);
 - 2. [search by api](https://api.scryfall.com/cards/search?q=++e:leb) return 292 cards (only one forest);
 - 3. [search by urlencoded api](https://api.scryfall.com/cards/search?q=%2B%2Be%3Aleb) (!?) return 302 cards (3 forests);

i'm using Firefox. 2 and 3 links looks same, but different results. Why?

**Comment by silasary** [comment]
A raw `+` is treated as a urlencoded space.

Your second search is technically searching for "  e:leb".
