### ISSUE TITLE
Something is weird with the name of Tidehollow Strix

### ISSUE THREAD

**Issue by jseakle** [scryfall/feedback#666]
the search "strix" finds it, but "re:strix" doesn't. similarly, "tidehollow" finds it, but "re:tidehollow" doesn't.

I wanted a results page with just all three strixen, and had to use "re:strix OR tidehollow strix"

**Comment by silasary** [comment]
`re:` only searches the oracle text.  As Tidehollow Strix doesn't mention its own name in the textbox, it doesn't show up in that search.

**Comment by jseakle** [comment]
Oh. Right.

I guess this is actually just another report about how it's really annoying that you can't get whitespace sensitivity in names. It should be possible to do some kind of simple search that returns the three strixen, but not Rotted Hystrix.

**Comment by csuhta** [comment]
You can now do regex against names: https://scryfall.com/search?q=name%3A%2F%5Cbstrix%2F
