### ISSUE TITLE
t:gus returns cards of type Fungus rather than Gus

### ISSUE THREAD

**Issue by Sniffnoy** [scryfall/feedback#667]
https://scryfall.com/search?q=t%3Agus

I would expect Gus (UGL) to come up, rather than non-extra cards of type Fungus.  Basically seems to me that if a type search returns no results, of the "try to match the type exactly" constraint and the "don't include extras" constraint, the latter should be relaxed first rather than the former.

Thank you!

**Comment by Sniffnoy** [comment]
Just noticed a similar problem occurs with t:urza (you get the lands of type Urza's rather than Urza from Unstable).

**Comment by cappert** [comment]
`t:urza is:funny` works like you suggest.
>[ Un-cards, holiday cards, and other funny cards are findable with is:funny or mentioning their set.](https://scryfall.com/docs/reference#extras)

**Comment by Sniffnoy** [comment]
I'm aware that "t:urza is:funny" works like I suggest; that's not my point, that doesn't change the fact that there's something wrong here.  There are multiple things that can cause extras to be included in results -- as you mention, putting things like "is:funny" or "include:extras" or "e:ust" or "e:arc" that explicitly trigger it are one way.  Another way, however, is when the search returns no results without extras.  Thus, for instance, "o:clothing" will return extras in its search, because without such there would be no results.

My point here is that the two fallback mechanisms -- allowing extras, and allowing substring matches on creature types -- are being applied in the wrong order.  The fact that I could also search "t:urzay is:funny" doesn't affect that.

**Comment by csuhta** [comment]
`t:gus` now also returns Gus. https://scryfall.com/search?q=t%3Agus
