### ISSUE TITLE
Getting 503s & 504s when loading images

### ISSUE THREAD

**Issue by Gonkers** [scryfall/feedback#670]
When using scryfall over the past few days it's been pretty unbearable. I've been getting a ton of 503s and 504s on the image requests.
---
503 Service Unavailable
504 Gateway Timeout
```
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```
![image](https://user-images.githubusercontent.com/8480646/34309105-4fe1759c-e71e-11e7-873b-cc35fa994dae.png)

Just thought I would bring it up if you if you didn't know about it.

**Comment by NilsEnevoldsen** [comment]
I'm getting this too. Probably related to what Corey said on Discord:

> Minor PSA: We have changed file storage providers for img.scryfall.com. The update should be transparent to you, but please report any weirdness

**Comment by soundslocke** [comment]
I've been noticing it lately as well, maybe every 10 pages or so an image doesn't load. I'm guessing whatever file storage change he posted about in Discord is related.

![image](https://user-images.githubusercontent.com/1626411/34457610-d5aae2f6-ed83-11e7-8558-f31941a8ca08.png)

**Comment by brine** [comment]
I’ve encountered this as well

**Comment by doppeldeveloper** [comment]
I get this or "503 please slow down"

**Comment by NilsEnevoldsen** [comment]
Team hasn't commented here, but is aware. @csuhta on Discord on 2017-12-30:

> Also still working on the intermitient image issues too

**Comment by csuhta** [comment]
Update on this: Our image host has resolved a week-long incident with accessing files: http://status.digitalocean.com/incidents/mb6rrjfcttzc

We're still seeing the occasional 503 "Slow Down" error (which we're also working with them to fix), but there should be no more image errors of other kinds now.
