### ISSUE TITLE
Report a problem not added into GitHub?

### ISSUE THREAD

**Issue by ancestral** [scryfall/feedback#673]
I added a couple of reports from Scryfall recently, and I noticed reports are no longer auto-added to the GitHub feedback. I’m guessing these may be filtered manually, and the actual problems are added by someone? But, this may be purely an assumption and not true.

**Comment by silasary** [comment]
The feedback form now goes to a private destination, due to people sending confidential details through it.

If you want followup for a report, it is recommended you manually post it here.
