### ISSUE TITLE
Typo in RIX card name - Orzaca Frillback

### ISSUE THREAD

**Issue by JayDi85** [scryfall/feedback#675]
[Orzaca Frillback](https://scryfall.com/card/rix/140) must be Orazca Frillback (see card image).

![shot_180106_085906](https://user-images.githubusercontent.com/8344157/34636645-dee71574-f2bf-11e7-83fc-096f2c1ed71f.png)

**Comment by tooomm** [comment]
Same here, see https://github.com/scryfall/feedback/issues/676#issuecomment-356051175

Both issues are still present on the page for me as well.

**Comment by tooomm** [comment]
Haha, they are fixed now 👍 😆 
Did you reported again via the site  @JayDi85?

**Comment by JayDi85** [comment]
@tooomm yes, I've report both cards by site.

**Comment by tooomm** [comment]
See, they are lightning fast then... I'm impressed.
Too bad they kinda abandon this repo it looks like.

Did you include a mail and got a response/info about the fixes?

**Comment by JayDi85** [comment]
@tooomm Yes, I'm post my mail on report, but no feedback from it.

**Comment by tooomm** [comment]
So no way to track/get informed about fixes anymore... that's bad. :(

**Comment by JayDi85** [comment]
@tooomm If you pay money to scryfall then you can get priority access to developer discord chat and full support. they are start to selling membership accounts.
