### ISSUE TITLE
What happens with the Random collage at home view?

### ISSUE THREAD

**Issue by yonkishum** [scryfall/feedback#677]
Hi, I know probably this feature it's not relevant but when you start the scryfall project on launch I like a lot that random collage at bottom of the page, now it's seems always show the same cards:

> Contraband Kingping, Highspire Infusion, Lovisa Coldeyes, Ajani Valiant Protector, Austere Command, Clash of Wills and Indulgent Aristocrat 

I hope you'll fix that 👍 thanks a lot Scryfall team 

![image](https://user-images.githubusercontent.com/6378461/34651439-a9188ab2-f3a6-11e7-838b-008ab6efc099.png)

**Comment by NilsEnevoldsen** [comment]
Sometimes it has a theme, although I can't always figure out what the theme is. Has it ever been truly random?

**Comment by yonkishum** [comment]
Ohh I see I always think that bottom was random, amazing job guys.

**Comment by csuhta** [comment]
The collage is not random, we change it up every so often manually with themes like Halloween or artists or featured sets
