### ISSUE TITLE
Update FAQ info about funny cards

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#686]
https://scryfall.com/docs/faqs

> **Where are the cards from Unglued, Unhinged, and the holidays?**
> They’re on the site, but because these cards are printed for fun and have a lot of strange text, they are excluded from search results by default. You must specifically search for them by adding is:funny to your terms, or searching for the set codes e:ugl, e:unh, and e:hho

This is no longer accurate. If it later becomes accurate again, UST should be added.

**Comment by JayDi85** [comment]
That's wrong. Default search works fine for that cards too. Goblin Tutor as example:
https://scryfall.com/search?q=Goblin+Tutor

**Comment by NilsEnevoldsen** [comment]
I think we're on the same page, @JayDi85. 👍

**Comment by csuhta** [comment]
Updated!
