### ISSUE TITLE
Leading and trailing whitespace not preserved in regular expressions

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#688]
* Leading whitespace not respected in regex query: [https://scryfall.com/search?q=o:/+orc/](https://scryfall.com/search?q=o:/+orc/
)
* Leading whitespace respected in string query: [https://scryfall.com/search?q=o:"+orc"](https://scryfall.com/search?q=o:"+orc")
* Interior whitespace respected in regex query: [https://scryfall.com/search?q=o:/t+he/](https://scryfall.com/search?q=o:/t+he/
)
* Interior whitespace respected in string query: [https://scryfall.com/search?q=o:"t+he"](https://scryfall.com/search?q=o:"t+he")

Expected: leading and trailing (as well as interior) whitespace respected in both types of queries.

**Comment by csuhta** [comment]
Regular expressions now correctly honor all whitespace within the `/ /`
