### ISSUE TITLE
Allow name:"foo" queries

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#690]
Currently the `name:` keyword is regex-only
* https://scryfall.com/search?q=name:/akroma/

For symmetry and clarity, I believe the keyword should work with simple strings as well
* [https://scryfall.com/search?q=name:"akroma"](https://scryfall.com/search?q=name:"akroma")
* https://scryfall.com/search?q=name:akroma

In addition to the extant "implicit keyword" style
* [https://scryfall.com/search?q="akroma"](https://scryfall.com/search?q="akroma")
* https://scryfall.com/search?q=akroma

**Comment by spacemonaut** [comment]
I imagine the "name" field as a string could/would be a punctuation-sensitive field?

**Comment by csuhta** [comment]
`name:""` is now available
