### ISSUE TITLE
API Recommendation for Links

### ISSUE THREAD

**Issue by Gonkers** [scryfall/feedback#691]
I would like to see you use an object for your `URI` links and use a collection to list them all when needed.

For example, if you had this object to define your links, it would make it more user friendly for those who consume your API.

```
{
  "name": "gatherer",
  "uri": "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=426912"
}
```
This...
```
  "related_uris": {
    "gatherer": "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=426912",
    "tcgplayer_decks": "http://decks.tcgplayer.com/magic/deck/search?contains=Dusk+%2F%2F+Dawn&page=1&partner=Scryfall",
    "edhrec": "http://edhrec.com/route/?cc=Dusk+%2F%2F+Dawn",
    "mtgtop8": "http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Dusk+%2F%2F+Dawn"
  }
```
Would become...
```
  "related_uris": [
    { "name": "gatherer", "uri": "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=426912" },
    { "name": "tcgplayer_decks", "uri": "http://decks.tcgplayer.com/magic/deck/search?contains=Dusk+%2F%2F+Dawn&page=1&partner=Scryfall" },
    { "name": "edhrec", "uri": "http://edhrec.com/route/?cc=Dusk+%2F%2F+Dawn" },
    { "name": "mtgtop8", "uri": "http://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Dusk+%2F%2F+Dawn" }
  ]
```

By doing so you could add or remove URI as needed and it would not result in a breaking change. This could also be used for `purchase_uris` and `image_uris`

Please consider,

Thanks.

**Comment by csuhta** [comment]
> By doing so you could add or remove URI as needed and it would not result in a breaking change. This could also be used for purchase_uris and image_uris

This isn't making sense to me. Can you elaborate? I don't see a benefit of the array over what we're currently doing.

**Comment by Gonkers** [comment]
The change is subtle I'll admit.

In my C# client I have to make a lot more rigid classes like this... 
```
using Newtonsoft.Json;

namespace ScryfallApi.Client.Models
{
    public class CardImageUris
    {
        [JsonProperty("small")]
        public string Small { get; set; }

        [JsonProperty("normal")]
        public string Normal { get; set; }

        [JsonProperty("large")]
        public string Large { get; set; }

        [JsonProperty("png")]
        public string Png { get; set; }

        [JsonProperty("art_crop")]
        public string ArtCrop { get; set; }

        [JsonProperty("border_crop")]
        public string BorderCrop { get; set; }
    }
}
```

It would be much easier for consumers to just need to define a class like this... 

```
using System;
using Newtonsoft.Json;

namespace ScryfallApi.Client.Models
{
    public class ScryfallUri
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("uri")]
        public Uri Uri { get; set; }
    }
}
```

Then everywhere I can just define I want an array of `ScryfallUri` objects and I don't have to worry about what URIs you add or remove.  My models won't _break_ if you were to remove one and I would get new links for "free", they would just get deserialized into my array.

My card class would change from 
```
[JsonProperty("image_uris")]
public CardImageUris ImageUris { get; set; }
```
to...
```
[JsonProperty("image_uris")]
public List<ScryfallUri> ImageUris { get; set; }
```

---

For a more concrete example, lets say you want to add a `jumbo` sized image that's 300 megapixels. In your current paradigm you will create a new entry `{ "jumbo": "https://www.bigimage.web/12.jpg" }`  This means I'll need to change my models to accommodate the new image, or retailer link, or xxx link. 

If it were an array, my application would just consume it without any changes and allow me to use it as I needed.  I hope that makes sense. 

Thanks for replying!

Gonkers

**Comment by doppeldeveloper** [comment]
If you want this behaviour then instead of deserialising these lists into defined objects, you should probably be deserialising them into a dictionary: https://stackoverflow.com/questions/1207731/how-can-i-deserialize-json-to-a-simple-dictionarystring-string-in-asp-net

**Comment by Gonkers** [comment]
Well thanks @doppeldeveloper ! 

I didn't realize json.net would deserialize to a dictionary like that.
