### ISSUE TITLE
provide recent ban lists

### ISSUE THREAD

**Issue by tooomm** [scryfall/feedback#693]
Is there a page on the website and a API call that return all banned cards?
Or all banned cards for a particular format?

Like https://api.scryfall.com/bannedcards, https://api.scryfall.com/banlists/modern
or https://scryfall.com/banlists.

**Comment by doppeldeveloper** [comment]
You can run an API search for cards matching a banned or restricted criteria: https://scryfall.com/docs/reference#legality fed into the cards/search endpoint: https://scryfall.com/docs/api/cards/search

E.g.

    https://api.scryfall.com/cards/search?order=cmc&q=banned%3Astandard

**Comment by csuhta** [comment]
What @doppeldeveloper said 😄

**Comment by tooomm** [comment]
Ok, that's cool. Thanks @doppeldeveloper, wasn't ware. 👍 

Works the same in a normal search on the website: https://scryfall.com/search?q=banned%3Astandard
It's actually described in the [syntax guide](https://scryfall.com/docs/reference) at `Format Legality`... 🙈
