### ISSUE TITLE
Cards in PHUK are mostly not considered to have new frames

### ISSUE THREAD

**Issue by Sniffnoy** [scryfall/feedback#695]
https://scryfall.com/search?q=%2B%2Be%3Aphuk+is%3Anew

Only this one card from PHUK is currently listed as having a new frame in the database.  Not sure what frame the others are listed as as they don't turn up under old either.  The entirety of the set should be listed as new frames.

**Comment by csuhta** [comment]
`is:new` is an alias for `frame:2015`. PHUK is the `2003` modern frame. 

Fixed Rats' Feast.

**Comment by Sniffnoy** [comment]
Oh I see, I thought `is:new` did what `is:modern` does.  Thanks!
