### ISSUE TITLE
Artist search should show every version of cards by that artist

### ISSUE THREAD

**Issue by thyeggman** [scryfall/feedback#7]
For example, searching (a:"Terese Nielsen") or (a:Terese a:Nielsen) shows the Eternal Masters version of Force of Will, but not the Alliances version, which was also done by Nielsen.

**Comment by csuhta** [comment]
You can use `++` to do this:

- https://scryfall.com/docs/reference#unrolling
- https://scryfall.com/search?as=&q=%2B%2Ba%3Aterese

**Comment by thyeggman** [comment]
Thanks for the syntax.  I guess my hope was that it would show every different art, but not every different version.  I don't know what the best way to solve this would be... Through syntax or with a checkbox in the advanced search page?

**Comment by csuhta** [comment]
We don't have a way to easily identify unique artworks, that would require some building some kind of hardcore image analysis tool. It will have to be `++` for now. Thanks for submitting a question!
