### ISSUE TITLE
Arts that are falsely reported as distinct

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#707]
* [ ] https://scryfall.com/card/4ed/357 is not distinct
* [ ] https://scryfall.com/card/6ed/220
* [ ] https://scryfall.com/card/6ed/202
* [ ] https://scryfall.com/card/6ed/207
* [ ] https://scryfall.com/card/8ed/34
* [ ] https://scryfall.com/card/cmd/255
* [ ] https://scryfall.com/card/hop/107
* [ ] https://scryfall.com/card/arc/104
* [ ] https://scryfall.com/card/arc/108
* [ ] https://scryfall.com/card/arc/117
* [ ] https://scryfall.com/card/prm/48190
* [ ] https://scryfall.com/card/prm/36070
* [ ] https://scryfall.com/card/prm/31477
* [ ] https://scryfall.com/card/prm/57608
* [ ] https://scryfall.com/card/td2/8
* [ ] https://scryfall.com/card/td2/24
* [ ] https://scryfall.com/card/td2/51

**Comment by gmac** [comment]
How did you find all of these, Nils? I can't think of a way beyond
paginating through our entire record set, or getting extremely lucky in
spot searches. Either way, thank you!

**Comment by NilsEnevoldsen** [comment]
"Informed elbow grease." Searches like `new:art is:reprint st:core -t:basic unique:prints order:set display:checklist`, and then looking for sets that only have a few hits, and seeing if those are genuine. Repeat for other set types, as appropriate.

The list above is not comprehensive, and PRM makes it harder than it otherwise would be.

**Comment by NilsEnevoldsen** [comment]
With access to the underlying database, one could pretty easily search through all nonbasic cards where one artist did different arts in different sets. That probably wouldn't be *too* long a list.

**Comment by gmac** [comment]
Interesting. My strategy in building the data was to create a record for
all distinct artist/oracle pairings, then I put together a quick and
disposable ui that displayed thumbnails of all illustration groups with two
or more printings. That got me down to about 20k records to visually
inspect, and split out differences among the groupings. Errors might occur
from human error in my visual inspection. Frequently the errors originate
from artist misprints that caused the prints to be grouped incorrectly in
the original assignments, and I may not have noticed the duplication was
paginating through the groupings. This project has surfaced many artist
misprints that I'm flagging with an archival note in our data.

**Comment by gmac** [comment]
This is fixed. Not sure why I don't have the ability to check checkboxes or close the ticket...

Thanks Nils, keep em' coming.
