### ISSUE TITLE
Cards missing artist information

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#709]
* [x] https://scryfall.com/card/prix/177 Kev Walker
* [x] https://scryfall.com/card/pz2/65803 Miao Aili
* [x] https://scryfall.com/card/pz2/65811 Miao Aili
* [x] https://scryfall.com/card/unh/44★ Dave Dorman
* [x] https://scryfall.com/card/j17/9 Dmitry Burmak
* [x] https://scryfall.com/card/hho/17 Dmitry Burmak
* [ ] https://scryfall.com/card/tvma/17 Ron Spears
* [ ] https://scryfall.com/card/tvma/9 E. M. Gist

**Comment by csuhta** [comment]
All fixed, thank you!
