### ISSUE TITLE
Automatic sort on EDHREC rank is the reverse of what is usually wanted

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#711]
"Bad cards first": https://scryfall.com/search?q=%2A&order=edhrec&as=checklist&unique=cards
"Good cards first": https://scryfall.com/search?q=%2A&order=edhrec&as=checklist&unique=cards&dir=asc

**Comment by spacemonaut** [comment]
Both of those links display the same thing to me. Auto = asc = good cards first. Sol ring being at the top makes sense, it'd be EDHREC rank 1 given it's the omnipresent staple of the format.

**Comment by NilsEnevoldsen** [comment]
Yep, works for me now as well. Stealth update?

**Comment by csuhta** [comment]
This has been fixed, "auto" for EDHREC is now ascending
