### ISSUE TITLE
Broken link in tagger.scryfall

### ISSUE THREAD

**Issue by mrandrewian** [scryfall/feedback#715]
From the page https://tagger.scryfall.com/tag/artwork/weatherlight-crew I clicked on the card "Distant Memories" which took me to https://tagger.scryfall.com/card/mbs/24.  That page is currently reporting a Heroku Application Error

I tried a bunch of different cards from that page and got to the same Application Error page.

![image](https://user-images.githubusercontent.com/697134/36277810-f4778ae4-125f-11e8-8db0-3ee27c362242.png)

**Comment by gmac** [comment]
Fixed.
