### ISSUE TITLE
Wrong artist on Demon token

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#720]
https://scryfall.com/card/tvma/4 is actually illustrated by Pete Venters.

**Comment by spacemonaut** [comment]
That link is broken.

**Comment by NilsEnevoldsen** [comment]
Uhhhhh what happened to TVMA? It gone…

**Comment by csuhta** [comment]
We actually removed TVMA completely yesterday. There were a few other internal issues with it and it needed to be re-rendered, but the main reason is that it's not actually a real Magic set. 

TVMA was a collection of renders a contributor gave us of the transient tokens that VMA cards produce on MTGO. You cannot actually obtain these tokens on MTGO or on paper. Scryfall only archives Magic cards you can collect and own. (For example, even though several cards produce Citizen tokens, WotC has never printed a collectable Citizen token)
