### ISSUE TITLE
Wrong artist on Order of the Ebon Hand (MED)

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#722]
https://scryfall.com/card/med/78 should be Christopher Rush

**Comment by NilsEnevoldsen** [comment]
Like #721, perhaps this is actually the wrong artwork?
 https://www.cardhoarder.com/cards/28009/med-order-of-the-ebon-hand

**Comment by gmac** [comment]
good catch. this is fixed.

**Comment by gmac** [comment]
Nope, not fixed. Consolidating with #721
