### ISSUE TITLE
Arts that are falsely reported as distinct

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#723]
A continuation of #707.

* [x] https://scryfall.com/card/prix/177s
* [x] https://scryfall.com/card/pz2/65861
* [x] https://scryfall.com/card/tc16/1
* [x] https://scryfall.com/card/tust/3 (I think?) 
* [x] https://scryfall.com/card/tpr/132
* [x] https://scryfall.com/card/vma/106
* [ ] https://scryfall.com/card/tvma/4 (also see #720)
* [x] https://scryfall.com/card/me4/130
* [x] https://scryfall.com/card/td0/B7
* [x] https://scryfall.com/card/td0/A13
* [x] https://scryfall.com/card/me3/199
* [x] https://scryfall.com/card/me2/13
* [x] https://scryfall.com/card/me2/111
* [x] https://scryfall.com/card/me2/193
* [x] https://scryfall.com/card/me2/173 (also see #721)
* [x] https://scryfall.com/card/pres/A10
* [x] https://scryfall.com/card/med/78 (also see #722)
* [x] https://scryfall.com/card/med/172
* [x] https://scryfall.com/card/me2/191
* [x] https://scryfall.com/card/5ed/37

Several of these are by Anthony S. Waters. Hmmm.

**Comment by NilsEnevoldsen** [comment]
BTW, @gmac, this list was created by trawling through the results of `new:art -new:artist`, skipping things like Alliances where is was obvious there would be a lot of false positives.

**Comment by gmac** [comment]
Thanks Nils, that's a clever search strategy

**Comment by gmac** [comment]
Should be set. Regarding the `Anthony S. Waters` issues, I suspect that's a case where an import brought his name in using different punctuation and was created as a separate artist. I've been working through merging artist variants recently and trying to get some import normalizations in place to prevent these sorts of subtle discrepancies.
