### ISSUE TITLE
UNH "★" prints are missing flavor text

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#729]
https://scryfall.com/saved/share?id=unh:9%E2%98%85/unh:20%E2%98%85/unh:43%E2%98%85/unh:44%E2%98%85/unh:49%E2%98%85/unh:67%E2%98%85/unh:78%E2%98%85/unh:82%E2%98%85/unh:90%E2%98%85/unh:101%E2%98%85/unh:103%E2%98%85/unh:104%E2%98%85/unh:106%E2%98%85/unh:109%E2%98%85/unh:121%E2%98%85/unh:122%E2%98%85/unh:123%E2%98%85/unh:125%E2%98%85

**Comment by jhallbachner** [comment]
This is the issue I meant to close, this is fixed now.
