### ISSUE TITLE
UNH prints have unrecognized watermarks

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#730]
Several UNH prints, such as https://scryfall.com/card/unh/124★, have watermarks, but are not is:watermark.

**Comment by gmac** [comment]
I've assigned them a generic `flavor` watermark. https://scryfall.com/search?q=wm%3Aflavor

**Comment by gmac** [comment]
Also, I'd be curious of your take on https://scryfall.com/card/unh/94 – is that actually a watermark? It could just be considered text box art.

**Comment by chuckharmston** [comment]
Asked the un-rules manager: https://twitter.com/scryfall/status/968498761256194050
