### ISSUE TITLE
Fix is:reprint and is:unique false positives

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#732]
https://scryfall.com/search?q=is:reprint+is:unique+include:extras+unique:prints

This returns 391 results. Some are non-unique reprints (like tokens and DDT cards). Some are non-reprint uniques (like Vanguard cards).

**Comment by csuhta** [comment]
This is a very broad ticket, is it possible to break it into smaller issues? Maybe with some examples of why a card in a group is incorrect?

**Comment by NilsEnevoldsen** [comment]
Alright, alright. I'll start in on that.

**Comment by NilsEnevoldsen** [comment]
Done.
