### ISSUE TITLE
More UNH prints with unrecognized watermarks

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#746]
Continuation of #730

* [x] ~https://scryfall.com/card/unh/72%E2%98%85 wm:WotC~
* [x] ~https://scryfall.com/card/unh/106%E2%98%85 wm:WotC~
* [ ] https://scryfall.com/card/unh/43%E2%98%85 Potentially wm:flavor
* [ ] https://scryfall.com/card/unh/43 Potentially wm:flavor
* [ ] https://scryfall.com/card/unh/128%E2%98%85 Potentially wm:flavor
* [ ] https://scryfall.com/card/unh/123%E2%98%85 wm:flavor (screw tip?)
* [ ] https://scryfall.com/card/unh/90%E2%98%85 wm:flavor (burn mark?)

Also, can watermarks ever exist outside a textbox? Things like https://scryfall.com/card/unh/122%E2%98%85 are kinda watermarky.

**Comment by csuhta** [comment]
The first two (shooting star in the bottom left corner) are specifically not watermarks, [per Rosewater](https://twitter.com/maro254/status/932288770950406144).

**Comment by NilsEnevoldsen** [comment]
Oops!

**Comment by NilsEnevoldsen** [comment]
Does that mean it should be removed from these?

* [ ] https://scryfall.com/card/pal99/1
* [ ] https://scryfall.com/card/pal99/3

**Comment by gmac** [comment]
I would give those other watermark proposals a 👎. I'd say a watermark is a single, central symbol in the background of the rules text box. Those are more background designs/patterns/extended artworks than they are watermarks IMHO.

**Comment by NilsEnevoldsen** [comment]
I can buy that. Feel free to close this issue at will.

**Comment by spacemonaut** [comment]
@gmac Mana Screw on this list looks like it might genuinely have a watermark: https://scryfall.com/card/unh/123★
