### ISSUE TITLE
API returns 404 for Gleemax Project (PGMX) and Promotional Planes (PHOP)

### ISSUE THREAD

**Issue by card-collector** [scryfall/feedback#75]
The set API returns both sets but the URLs it provides return no results.

 - [x] Gleemax Project [On site](https://scryfall.com/search?q=%2B%2Be%3Apgmx) - [API](https://api.scryfall.com/cards/search?order=set&q=%2B%2Be%3Apgmx)
 - [x] Promotional Planes [On site](https://scryfall.com/search?q=%2B%2Be%3Aphop) - [API](https://api.scryfall.com/cards/search?order=set&q=%2B%2Be%3Aphop)

**Comment by csuhta** [comment]
Fixed. Thanks for the report!
