### ISSUE TITLE
MCM link for Commander cards points to oversized version

### ISSUE THREAD

**Issue by chisui** [scryfall/feedback#751]
The *MagicCardMarket* links for the regular sized commander cards for which oversized versions exist point to it.

The Problem seems to be that they link to `(Version 2)` and not `(Version 1)`.

Examples:

[Animar](https://scryfall.com/card/cmd/181)

- **Wrong Version:** https://www.cardmarket.com/en/Magic/Products/Singles/Commander/Animar%2C+Soul+of+Elements+%28Version+2%29
- **Correct Version:** https://www.cardmarket.com/en/Magic/Products/Singles/Commander/Animar%2C+Soul+of+Elements+%28Version+1%29

[Oloro](https://scryfall.com/card/c13/203)

- **Wrong Version:** https://www.cardmarket.com/en/Magic/Products/Singles/Commander+2013/Oloro%2C+Ageless+Ascetic+%28Version+2%29
- **Correct Version:** https://www.cardmarket.com/en/Magic/Products/Singles/Commander+2013/Oloro%2C+Ageless+Ascetic+%28Version+1%29

**Comment by spacemonaut** [comment]
Same issue as #444

**Comment by NilsEnevoldsen** [comment]
This was fixed on March 17.
