### ISSUE TITLE
Allow queries for centered text

### ISSUE THREAD

**Issue by Subbarker** [scryfall/feedback#756]
perhaps `textalignment:centered`

**Comment by NilsEnevoldsen** [comment]
Comment from a Scryfall developer in Discord on March 24, 2018:

> I do not believe that this is something we'll offer.
> 
> Sorry to be a downer about it, but I don't want you to get your hopes up :neutral_face: It has very limited value, the data doesn't exist elsewhere and isn't derivable, and it adds something we need to check for every time we add a spoiler.
> 
> There is a future where we can tag printings, and this would be an excellent candidate for that.

So probably best to wontfix/close this issue.
