### ISSUE TITLE
Feature request: Card-level rarity search (equivalent of "in:" for rarity)

### ISSUE THREAD

**Issue by Sniffnoy** [scryfall/feedback#757]
Right now you can use "r:" to search printings by rarity.  What I'd like would be something that would let you see cards that have *ever* been printed at a certain rarity.  So you could do things like, search for cards that have been printed both at rare and at common, or both at mythic and at uncommon.

Thank you!

**Comment by NilsEnevoldsen** [comment]
Related to #47.

**Comment by Sniffnoy** [comment]
Yes, adding a general "exists a print with" quantifier would also work, and would stop little feature requests like these. :)

**Comment by csuhta** [comment]
This is now available: https://scryfall.com/search?q=in%3Auncommon
