### ISSUE TITLE
Negating fo: keyword doesn't work properly

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#769]
https://scryfall.com/search?q=-fo:"foobarbaz" has only 192 results (cards with multiples faces, etc).

**Comment by csuhta** [comment]
Fixed! :D 

https://scryfall.com/search?q=-fo:%22foobarbaz

**Comment by NilsEnevoldsen** [comment]
Hooray! What was going on here? I'm curious.

**Comment by csuhta** [comment]
Got burned again by the behavior of `NULL` in SQL
