### ISSUE TITLE
Thopter (TUST) isn't colored correctly

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#776]
It's blue, but should be colorless.

https://scryfall.com/card/tust/6

**Comment by NilsEnevoldsen** [comment]
Nevermind, maybe it actually is blue…? Where's the color indicator? I'm confused.

**Comment by csuhta** [comment]
The vast majority of tokens have no color indicator despite having their color set by the creating card. 

This token is another version of https://scryfall.com/card/tc16/9 which is blue. It's created by cards like [Thopter Foundry](https://scryfall.com/card/c16/237)

**Comment by NilsEnevoldsen** [comment]
Ohh, ordinary tokens don't have a color indicator either. So this is a colored artifact, which means it's additionally confusing, but it's consistent with other tokens. Got it.
