### ISSUE TITLE
"Gold" Dragon token is "WUBRG"

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#779]
Currently the "gold" Dragon token is assigned WUBRG colors. Short of adding "gold" to recognized Scryfall colors, I think it would be marginally more accurate to remove these colors (making the token effectively "colorless"), because the token is not W, U, B, R, or G.

https://scryfall.com/card/tust/16
https://scryfall.com/card/h17/4

**Comment by gmac** [comment]
Updated
