### ISSUE TITLE
Analytics resource blocked by CSP

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#780]
Issue:

```Refused to load the script 'data:application/javascript;base64,…==' because it violates the following Content Security Policy directive: "script-src assets.scryfall.com checkout.stripe.com www.google-analytics.com 'unsafe-eval' 'self'".```

Solution:

Add `data:` to the `script-src` CSP.

**Comment by csuhta** [comment]
I do not see any errors, what browser and operating system are you using?

**Comment by NilsEnevoldsen** [comment]
macOS High Sierra and Chrome. I will investigate further.

**Comment by csuhta** [comment]
I suspect you have a misbehaving browser extension

**Comment by NilsEnevoldsen** [comment]
Sorry, yes, uBlock Origin. There was an enabled privacy filter that wasn't in the "privacy" section.

https://nanch.com/blog/20160908.csp.data.javascript says:

> You're seeing that error because you have an ad-blocking extension installed (Ghostery or uBlock Origin) and the extension replaces the google analytics script with an inline base64 script - which is not allowed by your Content Security Policy.

I did not know this was a thing. I wonder how it works.
