### ISSUE TITLE
Card Names catalog should not return emblems

### ISSUE THREAD

**Issue by dlras2** [scryfall/feedback#782]
Getting `/catalog/card-names` returns emblem names, e.g. Tezzeret the Schemer Emblem. These emblems, for all intents and purposes, are like "token" cards—card-like pieces of cardboard that can optionally be used to represent game objects, and not cards themselves—and including them in this list seems unintuitive.

**Comment by csuhta** [comment]
Fixed, also removed these items too: https://scryfall.com/search?as=&q=t%3Acard

https://api.scryfall.com/catalog/card-names?pretty=true
