### ISSUE TITLE
Card Names catalog should return combined multiface names

### ISSUE THREAD

**Issue by dlras2** [scryfall/feedback#783]
Getting `/catalog/card-names` returns the names of multiface cards separated from each other, e.g. Bound and, in a separate entry, Determined. This runs contrary to the rest of the API. For example, getting `/cards/named?exact=Bound` returns an object with the name "Bound // Determined", and not two objects, nor a single object with just half the combined name. Additionally, by including "Bound // Determined" instead of each name individually, the `/catalog/card-names` can will provide additional useful information that would otherwise require further API calls. The catalog endpoint doesn't lose any functionality as consumers could infer that all pieces of the multifaced card are also valid card names.

Notably, "Who // What // When // Where // Why" is already returned as a single entry.

**Comment by csuhta** [comment]
Fixed https://api.scryfall.com/catalog/card-names?pretty=true
