### ISSUE TITLE
Some "creatures" should be spells but aren't

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#787]
- [x] https://scryfall.com/card/pcel/2
- [x] https://scryfall.com/card/unh/1
- [x] https://scryfall.com/card/unh/106
- [x] https://scryfall.com/card/unh/106%E2%98%85
- [x] https://scryfall.com/card/pcel/1

These don't show up for `is:spell`

**Comment by csuhta** [comment]
Fixed
