### ISSUE TITLE
A list of artist pseudonyms

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#789]
I don't think this list is comprehensive, but it might help.

In all these cases, I think searching for any variant of the artist name should return all cards by the artist.

Variants:
- https://scryfall.com/search?q=a:"randy+asplund"& and https://scryfall.com/search?q=a:"randy+asplund-faith"&
- https://scryfall.com/search?q=a:"edward+p.+beard,+jr."& and https://scryfall.com/search?q=a:"edward+beard,+jr."&
- https://scryfall.com/search?q=a:"geofrey+darrow"& and https://scryfall.com/search?q=a:"g.+darrow"&
- https://scryfall.com/search?q=a:"diterlizzi"& and https://scryfall.com/search?q=a:"tony+diterlizzi"&
- https://scryfall.com/search?q=a:"inoue+junichi"& and https://scryfall.com/search?q=a:"junichi+inoue"&
- https://scryfall.com/search?q=a:"pat+lewis"& and https://scryfall.com/search?q=a:"pat+morrissey"&
- https://scryfall.com/search?q=a:"dany+orizio"& and https://scryfall.com/search?q=a:"orizio+daniele"&
- https://scryfall.com/search?q=a:"parente"& and https://scryfall.com/search?q=a:"paolo+parente"&
- https://scryfall.com/search?q=a:"dave+seeley"& and https://scryfall.com/search?q=a:"david+seeley"&
- https://scryfall.com/search?q=a:"kev+walker"& and https://scryfall.com/search?q=a:"kevin+walker"&
- https://scryfall.com/search?q=a:"anthony+s.+waters"& and https://scryfall.com/search?q=a:"anthony+waters"&
- https://scryfall.com/search?q=a:"steve+white"& and https://scryfall.com/search?q=a:"steven+white"&
- https://scryfall.com/search?q=a:"allen+williams"& and https://scryfall.com/search?q=a:"l.+a.+williams"&

Black-border pseudonyms:
- https://scryfall.com/search?q=a:"robert+bliss"& and https://scryfall.com/search?q=a:"chengo+mcflingers"&
- https://scryfall.com/search?q=a:"heather+hudson"& and https://scryfall.com/search?q=a:"erica+gassalasca-jape"&

Misspellings:
- https://scryfall.com/search?q=a:"dennis+detwiller"& and https://scryfall.com/search?q=a:"denise+detwiller"& and https://scryfall.com/search?q=a:"denise+detwiler"&
- https://scryfall.com/search?q=a:"douglas+shuler"& and https://scryfall.com/search?q=a:"douglas+schuler"&
- https://scryfall.com/search?q=a:"bryon+wackwitz"& and https://scryfall.com/search?q=a:"byron+wackwitz"&

Silver-border nonsense:
- Too many to list

Homonyms:
- The John Howe who did https://scryfall.com/card/eve/101 and https://scryfall.com/card/lrw/269 is not the John Howe who did all other illustrations (https://scryfall.com/search?q=a:"john+howe"+-b:lrw+-b:shm). I feel like that distinction should be made, but I'm not sure how.

**Comment by csuhta** [comment]
We intentionally list an alias for the funny cards. The other issues though should be fixed (the artists combined, etc)

**Comment by NilsEnevoldsen** [comment]
Perhaps I misunderstand what you're saying about funny cards, but wouldn't users expect that a search for, e.g., `a:"Kev Walker"` would find [Atinlay Igpay](https://scryfall.com/card/unh/1)?

**Comment by gmac** [comment]
Is that some kind of letter scramble that is actually Kev Walker? If so, we
just need to adjust the artist config and alias on that card

**Comment by NilsEnevoldsen** [comment]
Yes, it's "Kev Walker" in pig latin.

I expect to find the same results regardless of whether I search for `a:"kev walker"` or `a:"kevin walker"` or `a:"evkay alkerway"`.

**Comment by gmac** [comment]
More information in this thread: https://www.reddit.com/r/magicTCG/comments/36hnbp/magic_artists_that_have_different_names_on/

**Comment by NilsEnevoldsen** [comment]
Lovely! Looks like this is all done. 🎉

**Comment by gmac** [comment]
I've been working my way slowly towards closing this. I still have a few artist names left to configure for specific printings. I think the last thing on my list is to assign `Pat Morrissey` as the display name on her printings.

**Comment by gmac** [comment]
Also Nils – artist misprints have been flagged throughout this process, so you can see things like all Douglas Shuler cards with his name misspelled https://scryfall.com/search?q=%2B%2Ba%3AShuler+is%3Aartistmisprint

**Comment by NilsEnevoldsen** [comment]
Looks great, @gmac! How did you get all the Tim/Greg Hildebrandt misprints straightened out? That seems… subtle.

And is this really a misprint? https://scryfall.com/card/tpr/132

**Comment by gmac** [comment]
AH – good catch on https://scryfall.com/card/tpr/132. That was flagged as a misprint before Allen and L. A. Williams were reconciled. I've removed its artist misprint flag.

For Greg and Tim Hildebrandt, most of that was sussed out by you and others who reported duplicate illustrations in our dataset. About 90% of the time, those duplicate illustrations are a result of an artist name misprint which creates a new artist/card pairing assumed to be unique. The illustration dataset really helped to clean up the artist dataset, which should in turn really help to cleanup the creation of unique illustrations. These two datasets have proved extremely symbiotic.

**Comment by NilsEnevoldsen** [comment]
Aha, I should have realized that all the misprinted Hildebrandts were reprints that have different artist credits. Nice.
