### ISSUE TITLE
"Saved cards" has no mobile search controls

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#791]
At widths below 860px, the `search-controls` banner is un-displayed and the `search-controls-mobile` banner is displayed. But on the Saved Cards page, there is no `search-controls-mobile` banner, so instead the functionality it contains disappears. Thus there's no way, e.g., to share a link on mobile.

**Comment by gmac** [comment]
Saved cards is in the process of changing a whole lot. We're not putting any effort into old saved cards.
