### ISSUE TITLE
Queries of the form t:"foo bar" return confusing results

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#794]
I'd argue for reopening https://github.com/scryfall/feedback/issues/82. This has been seen in the wild, e.g. https://www.reddit.com/r/magicTCG/comments/85czoy/neat_little_game_ive_been_playing_with_my_friends/dvycvve/. A user on Discord ran into the same issue. I'd say that's evidence that it's not esoteric. In addition, searching for things like `t:"legendary artifact"` seems like a normal thing to do.

There are a few related issues:

- When the printed type is `foo bar`, searching for `t:"foo bar"` won't find it and `t:"bar foo"` will. (Because the Scryfall typeline is seemingly alphabetized.)
- This can lead to seemingly odd results. E.g. `s:rtr t:"legendary creature"` finds two of the five RTR guild leaders and `s:rtr t:creature t:legendary` finds all five.
- It's questionable whether the typeline is an ordered list at all, and whether searching for `t:"foo bar"` has any meaning.

There are a few possible resolutions:

- Disallow queries of the form `t:"foo bar"`. (Any `type:` query with a space?)
- Match only the Oracle order of types. (Judgment call: Is the dash part of the typeline?)
- Try to be smart, and match `t:"foo bar"` to any card with a type that ends in `foo` and a type that begins in `bar`.

**Comment by spacemonaut** [comment]
I would make `t:"a b c"` equivalent to `t:a t:b t:c`. It's going to correspond functionally to what people mean to find most of the time, I'd guess.

**Comment by csuhta** [comment]
This now works correctly with quotes:

- https://scryfall.com/search?as=&q=t%3A%22enchantment%20artifact%22
- https://scryfall.com/search?as=&q=s%3Artr%20t%3A%22legendary%20creature%22

Note that if you use quotes, the system searches strictly on you input:

- https://scryfall.com/search?q=t%3A%22creature+artifact%22
- https://scryfall.com/search?q=t%3A%22artifact+creature%22

**Comment by NilsEnevoldsen** [comment]
And for the record, it looks like the dash is a literal m-dash in such cases:

* https://scryfall.com/search?q=t:“artifact+creature+—+construct”
* https://scryfall.com/search?q=t:“artifact+creature+-+construct”

**Comment by DragonXDoom** [comment]
Just chiming in here to say that I tried [https://scryfall.com/search?q=t:"tribal+equipment"](https://scryfall.com/search?q=t%3A%22tribal+equipment%22) today and was rather surprised when it didn't return anything. This syntax worked on magiccards.info (where the syntax is very similar).

As @spacemonaut mentioned above, I would much prefer if `t:"a b c"` was equivalent to `t:a t:b t:c`.
