### ISSUE TITLE
Tertiary sort criterion is wrong with order:release

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#798]
`order:release` uses the order hierarchy "release_date descending, set descending, collector_number descending, name descending"

However, the "collector_number descending" is using an alphanumeric sort: 198, 199, 2, 21, etc.

https://scryfall.com/search?q=e:a25+c=b&order=released&as=checklist&unique=cards

**Comment by spacemonaut** [comment]
I think the issue shows up a lot better in the whole set view:

https://scryfall.com/sets/a25?as=checklist&order=released

**Comment by csuhta** [comment]
This should be fixed
