### ISSUE TITLE
A25 not listed as available on MTGO

### ISSUE THREAD

**Issue by Sniffnoy** [scryfall/feedback#799]
A25 is available on Magic Online, but isn't listed as such here: https://scryfall.com/search?q=e%3Aa25+game%3Amtgo&unique=cards&as=grid&order=name

In particularly this is noteworthy because it causes `f:vintage -in:mtgo` to return the wrong result -- A25 introduced Deadly Designs to Magic Online, but the database still thinks Deadly Designs has not appeared on MTGO.

**Comment by csuhta** [comment]
Fixed
