### ISSUE TITLE
Incorrect frame information for many sets

### ISSUE THREAD

**Issue by csuhta** [scryfall/feedback#8]
The TD0 set contains both 1993 and 2003 frames, need to manually set the correct frame for each card.

https://scryfall.com/search?q=%2B%2Be%3Atd0

**Comment by XVicarious** [comment]
I'm going to add to this, other sets, namely promo sets have this issue as well.

* ppre (has cards with frames 1993, 2003, and 2015)  
* pmei (has cards with frames 1993, 2003 and 2015)  
* f15 (only cards with 2015 frames, at least some are listed as 1993 frames)  
* f10 (only cards with 2003 frames, at least some are listed as 1993 frames)  
* f12 (this seems to be a theme with these FNM promo sets)  

Actually. The following query is by no means complete and I'm sure it could be smaller using block notation, but this lists 987 cards most of which are comprised of the aforementioned sets among others.

`++frame:1993 -s:f01 -s:palp -s:jgp -s:g03 -s:g02 -s:g00 -s:g01 -s:fnm -s:f02 -s:pelp -s:ugl -s:plgm -s:ppod -s:mgb -s:wth -s:drk -s:med -s:me2 -s:me3 -s:me4 -s:ptk -s:atq -s:jud -s:mmq -s:rqs -s:itp -s:sth -s:ath -s:apc -s:leb -s:lea -s:2ed -s:s00 -s:por -s:3ed -s:pls -s:p02 -s:btd -s:vis -s:brb -s:dkm -s:s99 -s:lgn -s:all -s:exo -s:fem -s:usg -s:ice -s:tor -s:arn -s:ons -s:leg -s:scg -s:nem -s:mir -s:ulg -s:chr -s:inv -s:pcy -s:uds -s:tmp -s:ody -s:4ed -s:5ed -s:6ed -s:7ed -s:hml`

**Comment by csuhta** [comment]
@XVicarious Thanks for the thorough report on this

**Comment by NilsEnevoldsen** [comment]
VMA is frame:2003. Should be frame:2015.

**Comment by gmac** [comment]
TD0 is done:

https://scryfall.com/search?q=%2B%2Be%3Atd0+frame%3A2003
https://scryfall.com/search?q=%2B%2Be%3Atd0+frame%3A1993

**Comment by gmac** [comment]
VMA appears to be done:

https://scryfall.com/search?q=%2B%2Be%3Avma+frame%3A2015

I didn't make changes here (maybe Corey did?). @NilsEnevoldsen – please confirm VMA looks right.

**Comment by csuhta** [comment]
Yes, sorry. I mass-updated VMA and forgot to comment.

**Comment by csuhta** [comment]
@gmac If any of the sets need _all cards_ in the set changed to a different frame, let me know. I can do that really fast with a database query. The only ones we need to hand-edit are the sets that have different frames within the same set.

**Comment by gmac** [comment]
Yep. ^^

**Comment by gmac** [comment]
I've done a massive sweep through promo sets and corrected all mislabeled card frames that I could find. The Scryfall database should be in much better shape (though I'm sure there are some that I missed). Closing this ticket. Please open a new ticket per set for any that still have frame issues.
