### ISSUE TITLE
Memorial to Glory

### ISSUE THREAD

**Issue by ThAlEdison** [scryfall/feedback#801]
Oracle text currently reads:
"Memorial to Glory enters the battlefield tapped.

{T}: Add {W}.

{3}{W}, {T}, Sacrifice Memorial to Glory: Creature two 1/1 white Soldier creature tokens."

It should read:
"Memorial to Glory enters the battlefield tapped.

{T}: Add {W}.

{3}{W}, {T}, Sacrifice Memorial to Glory: Create two 1/1 white Soldier creature tokens."

The word creature is  used instead of the word create.

**Comment by csuhta** [comment]
Fixed
