### ISSUE TITLE
Bug with Dominaria searching?

### ISSUE THREAD

**Issue by ThAlEdison** [scryfall/feedback#803]
When I run the search 's:dom s:ema' 0 results are returned.
However, 's:dom "Llanowar Elves"' and 's:ema "Llanowar Elves"'

**Comment by ThAlEdison** [comment]
The two name-specific searches both return correctly.

**Comment by NilsEnevoldsen** [comment]
I believe you want the query `in:dom in:ema`.

**Comment by ThAlEdison** [comment]
Actually combining two set searches looks like it doesn't work. So, that just might be my improper understanding of the syntax for what I want to do.

**Comment by NilsEnevoldsen** [comment]
`set:` is a property of the specific _printing_. So a _printing_ in DOM can't also be a _printing_ in EMA. `in:` is a property of the _card_. So a card that has a printing in DOM can also have a printing in EMA.
