### ISSUE TITLE
is:funny returns PCEL cards that aren't, well, funny

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#804]
https://scryfall.com/search?q=is:funny+s:pcel

While admittedly subjective, I don't think PCEL cards other than Robot Chicken should count as "funny" cards.

**Comment by gmac** [comment]
Hu, I'd disagree. They seem appropriately "funny" and meta-ish in the same spirit as silver bordered cards.

**Comment by NilsEnevoldsen** [comment]
Even Shichifukujin Dragon? (I'd argue for others, but Shichifukujin Dragon seems like the clearest not-funny card there.)

**Comment by csuhta** [comment]
On Scryfall, "funny" means more like "This card was printed as a joke or for someone's amusement". But more importantly, "funny" is a taxonomy we use to filter these kinds of non-constructed cards away from regular results.
