### ISSUE TITLE
Changling prompt does not appear when using some preference keywords

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#812]
Changling prompt shown:

* https://scryfall.com/search?q=t:merfolk
* https://scryfall.com/search?q=t:merfolk&unique=prints
* https://scryfall.com/search?q=t:merfolk&display=text
* https://scryfall.com/search?q=t:merfolk&order=released

Changling prompt not shown:

* https://scryfall.com/search?q=t:merfolk+unique:prints
* https://scryfall.com/search?q=t:merfolk+display:text
* https://scryfall.com/search?q=t:merfolk+order:released

**Comment by csuhta** [comment]
This is intentional. We only show the prompt on extremely simple searches. If you're using the control keywords we assume you're an expert:tm:
