### ISSUE TITLE
Add scryfall.com to twofactorauth.org

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#814]
https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md

twofactorauth.org is a list of websites and whether or not they support 2FA.

**Comment by csuhta** [comment]
Feel free to submit us! (This feels kind of Wikipedia-ish where companies submittting themselves would be self-serving)

**Comment by NilsEnevoldsen** [comment]
https://github.com/2factorauth/twofactorauth/pull/3176

**Comment by gmac** [comment]
thanks Nils!
