### ISSUE TITLE
Add cards/count API endpoint

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#815]
I don't suppose there're plans for a cards/count endpoint, eh?  It might be handy for things like trying to figure out how viable a Gruul commander deck featuring only cards with art by Rebecca Guay and Terese Nielsen would be (while minimizing load and traffic)

The `total_cards` parameter totally works, I was just wondering about a separate endpoint so the server doesn't have to generate and send the whole list (or first page thereof)

(Posted on behalf of Interpunkt.)

**Comment by NilsEnevoldsen** [comment]
Potentially related to #422.

**Comment by gmac** [comment]
We appreciate the concern for our servers, but honestly – it's better for us to focus on good, general purpose endpoints than optimized use cases. Request away.
