### ISSUE TITLE
Hanweir Garrison (EMN) is missing flavor text

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#818]
https://scryfall.com/card/emn/130a

**Comment by NilsEnevoldsen** [comment]
(https://scryfall.com/card/pemn/130as as well)

**Comment by gmac** [comment]
Added

**Comment by spacemonaut** [comment]
Penn/130as is still missing the flavor text

**Comment by NilsEnevoldsen** [comment]
I opened a new issue for it, @spacemonaut. Thanks!

**Comment by gmac** [comment]
wat? hu, something must not have saved. sorry about that.
