### ISSUE TITLE
Can't Search for creatures with type, "Enchantment Creature"

### ISSUE THREAD

**Issue by josephprice** [scryfall/feedback#82]
<img width="799" alt="t__enchantment_creature__ _scryfall_magic_card_search_and_t__creature_enchantment__ _scryfall_magic_card_search_and_hmi__compatibility_mode_" src="https://cloud.githubusercontent.com/assets/1693480/26560176/779186d4-4482-11e7-98ae-85a45ceed6e8.png">

Strange behavior doing searches for creatures with ' t:"enchantment creature" '. It shows no results.

Strangely, ' t:"creature enchantment" ' works fine.

' t:"artifact creature" ' also works fine.

**Comment by gmac** [comment]
The official syntax would be `t:creature t:enchantment`, see https://scryfall.com/search?q=t%3Acreature+t%3Aenchantment.

**Comment by csuhta** [comment]
@josephprice In your opinion, what _should_ happen here? 

1. Both `t:"creature enchantment"` and `t:"enchantment creature"` should return cards
2. Only `t:"enchantment creature"` should return something because that's the phrasing on the cards
3. Neither should return anything

**Comment by josephprice** [comment]
I think 2. best matches expectations, right? That's how we enforce quotes around Oracle text.

**Comment by csuhta** [comment]
Ok, that's perfect. Will fix.

**Comment by doppeldeveloper** [comment]
Related, [there's never been a "creature enchantment" card](https://scryfall.com/search?q=t%3Aenchantment+t%3Acreature+-b%3Aths) -- they've always been printed as "enchantment creature".

**Comment by doppeldeveloper** [comment]
This bug manifests in some other ways:

Theros legendary enchantment artifacts:

- [`t:"legendary enchantment artifact"`](https://scryfall.com/search?q=t%3A%22legendary+enchantment+artifact%22) (0 results) vs [`t:legendary t:enchantment t:artifact`](https://scryfall.com/search?q=t%3Alegendary+t%3Aenchantment+t%3Aartifact) (5 results)
- [`t:"enchantment artifact"`](https://scryfall.com/search?q=t%3A%22enchantment+artifact%22) (0 results) vs [`t:enchantment t:artifact`](https://scryfall.com/search?q=t%3Aenchantment+t%3Aartifact) (5 results)

[`t:"artifact enchantment"`](https://scryfall.com/search?q=t%3A%22artifact+enchantment%22) and [`t:"artifact enchantment legendary"`](https://scryfall.com/search?q=t%3A%22artifact+enchantment+legendary%22) both provide the correct 5 results despite not being the order printed on the card) so I'm guessing the system expects to see the types in alphabetical order.

[`t:"legendary artifact"`](https://scryfall.com/search?q=t%3A%22legendary+artifact%22) doesn't show any results; [`t:"artifact legendary"`](https://scryfall.com/search?q=t%3A%22artifact+legendary%22) does and so does [`t:artifact t:legendary`](https://scryfall.com/search?q=t%3Aartifact+t%3Alegendary).

**Comment by chuckharmston** [comment]
Open to disagreement, but I'm going to close this.

It's relatively complicated, highly esoteric, and not practically helpful, as the specific order of types on a card does not impact rules or classification.

**Comment by csuhta** [comment]
This now works correctly with quotes:

- https://scryfall.com/search?as=&q=t%3A%22enchantment%20artifact%22
- https://scryfall.com/search?as=&q=s%3Artr%20t%3A%22legendary%20creature%22

Note that if you use quotes, the system searches strictly on you input:

- https://scryfall.com/search?q=t%3A%22creature+artifact%22
- https://scryfall.com/search?q=t%3A%22artifact+creature%22
