### ISSUE TITLE
Discord Scrybot FR - Link pictures 

### ISSUE THREAD

**Issue by hazel-havard** [scryfall/feedback#822]
When Scrybot is invoked with `[[foo]]`, would it be possible for the small image displayed to the right of the rules text to link to the card image, similar to what happens when invoked with `[[!foo]]`?  This would allow extensions like [imagus](https://chrome.google.com/webstore/detail/imagus/immpkjjlgappgfkkfieppnmlhakdmaab?hl=en) to expand the image on hover.

I'm thinking just the little thumbnail would link to the image file, the card name would still link to the card on scryfall.

**Comment by csuhta** [comment]
It's not possible for us to provide this. For the "thumbnail"-style Discord message (i.e. a link with a title, description, and image) Discord's only allow submitting one link for the entire message and one URL to an image file to use as the thumbnail. We can't connect multiple links this way in one message, sorry!

**Comment by hazel-havard** [comment]
@csuhta Oh interesting, I didn't realize there was such a limitation.  Thanks for letting me know!
