### ISSUE TITLE
Add text to Checklist cards

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#826]
Checklist cards should have text!

*****

https://scryfall.com/card/trix/CH1

_(You can mark this card to represent a double-faced card in your library or hand.)_

☐ Hadana's Climb {1}{G}{U}
☐ Journey to Eternity {1}{B}{G}
☐ Path of Mettle {R}{W}
☐ Profane Procession {1}{W}{B}
☐ Storm the Vault {2}{U}{R}
☐ Azor's Gateway {2}
☐ Golden Guardian {4}

*****

https://scryfall.com/card/txln/CH1

_(You can mark this card to represent a double-faced card in your library or hand.)_

☐ Legion's Landing {W}
☐ Search for Azcanta {1}{U}
☐ Arguel's Blood Fast {1}{B}
☐ Vance's Blasting Cannons {3}{R}
☐ Growing Rites of Itlimoc {2}{G}

☐ Conqueror's Galleon {4}
☐ Dowsing Dagger {2}
☐ Primal Amulet {4}
☐ Thaumatic Compass {2}
☐ Treasure Map {2}

*****

https://scryfall.com/card/temn/11

_(You can mark this card to represent a meld or double-faced card in your library or hand.)_

☐ Bruna, the Fading Light {5}{W}{W}
☐ Extricator of Sin {2}{W}
☐ Gisela, the Broken Blade {2}{W}{W}
☐ Lone Rider {1}{W}
☐ Curious Homunculus {1}{U}
☐ Docent of Perfection {3}{U}{U}
☐ Grizzled Angler {2}{U}
☐ Graf Rats {1}{B}
☐ Midnight Scavengers {4}{B}
☐ Voldaren Pariah {3}{B}{B}
☐ Conduit of Storms {2}{R}
☐ Hanweir Garrison {2}{R}
☐ Smoldering Werewolf {2}{R}{R}
☐ Vildin-Pack Outcast {4}{R}
☐ Kessig Prowler {G}
☐ Shrill Howler {2}{G}
☐ Tangleclaw Werewolf {2}{G}{G}
☐ Ulvenwald Captive {1}{G}
☐ Ulrich of the Krallenhorde {3}{R}{G}
☐ Cryptolith Fragment {3}
☐ Hanweir Battlements

*****

https://scryfall.com/card/tsoi/20

_(You can mark this card to represent a double-faced card in your library or hand.)_

☐ Archangel Avacyn {3}{W}{W}
☐ Hanweir Militia Captain {1}{W}
☐ Startled Awake {2}{U}{U}
☐ Thing in the Ice {1}{U}
☐ Elusive Tormentor {2}{B}{B}
☐ Geier Reach Bandit {2}{R}
☐ Sage of Ancient Lore {4}{G}
☐ Arlinn Kord {2}{R}{G}
☐ Westvale Abbey

*****

https://scryfall.com/card/tsoi/19

_(You can mark this card to represent a double-faced card in your library or hand.)_

☐ Avacynian Missionaries {3}{W}
☐ Pious Evangel {2}{W}
☐ Town Gossipmonger {W}
☐ Aberrant Researcher {3}{U}
☐ Daring Sleuth {1}{U}
☐ Uninvited Geist {2}{U}
☐ Accursed Witch {3}{B}
☐ Heir of Falkenrath {1}{B}
☐ Kindly Stranger {2}{B}
☐ Breakneck Rider {1}{R}{R}
☐ Convicted Killer {2}{R}
☐ Gatstaf Arsonists {4}{R}
☐ Kessig Forgemaster {1}{R}
☐ Skin Invasion {1}{R}
☐ Village Messenger {R}
☐ Autumnal Gloom {2}{G}
☐ Duskwatch Recruiter {1}{G}
☐ Hermit of the Natterknolls {2}{G}
☐ Hinterland Logger {1}{G}
☐ Lambholt Pacifist {1}{G}
☐ Solitary Hunter {3}{G}
☐ Harvest Hand {3}
☐ Neglected Heirloom {1}
☐ Thraben Gargoyle {1}

*****

https://scryfall.com/card/tori/15

_(You can mark this card to represent a double-faced Planeswalker card in your library or hand.)_

☐ Kytheon, Hero of Akros {W}
☐ Jace, Vryn's Prodigy {1}{U}
☐ Liliana, Heretical Healer {1}{B}{B}
☐ Chandra, Fire of Kaladesh {1}{R}{R}
☐ Nissa, Vastwood Seer {2}{G}

*****

https://scryfall.com/card/tdka/4

_(You can mark this card to represent a double-faced card in your library or hand.)_

☐ Loyal Cather {W}{W}
☐ Soul Seizer {3}{U}{U}
☐ Chosen of Markov {2}{B}
☐ Ravenous Demon {3}{B}{B}
☐ Afflicted Deserter {3}{R}
☐ Hinterland Hermit {1}{R}
☐ Mondronen Shaman {3}{R}
☐ Lambholt Elder {2}{G}
☐ Scorned Villager {1}{G}
☐ Wolfbitten Captive {G}
☐ Huntmaster of the Fells {2}{R}{G}
☐ Chalice of Life {3}
☐ Elbrus, the Binding Blade {7}

*****

https://scryfall.com/card/tisd/13

_(You can mark this card to represent a double-faced card in your library or hand.)_

☐ Cloistered Youth {1}{W}
☐ Thraben Sentry {3}{W}
☐ Civilized Scholar {2}{U}
☐ Delver of Secrets {U}
☐ Ludevic's Test Subject {1}{U}
☐ Bloodline Keeper {2}{B}{B}
☐ Screeching Bat {2}{B}
☐ Hanweir Watchkeep {2}{R}
☐ Instigator Gang {3}{R}
☐ Kruin Outlaw {1}{R}{R}
☐ Reckless Waif {R}
☐ Tormented Pariah {3}{R}
☐ Village Ironsmith {1}{R}
☐ Daybreak Ranger {2}{G}
☐ Garruk Relentless {3}{G}
☐ Gatstaf Shepherd {1}{G}
☐ Grizzled Outcasts {4}{G}
☐ Mayor of Avabruck {1}{G}
☐ Ulvenwald Mystics {2}{G}{G}
☐ Villagers of Estwald {2}{G}

*****

**Comment by gmac** [comment]
Doh, all checklists share an oracle card at the moment. This is a bigger update than I originally thought it would be.

**Comment by gmac** [comment]
done https://scryfall.com/search?q=Checklist
