### ISSUE TITLE
Some bio transcriptions

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#828]
@gmac 

https://scryfall.com/card/wc03/we0a

Wolfgang Eder introduced this black-red “Goblin Bidding” deck to the world at this year’s European Championships. The twenty-two-year-old student from Weinheim, Germany, says the inspiration for the deck came from trying to give the typical Goblin tribe something to do in the midgame. He achieved this by adding black to the deck for Patriarch’s Bidding, which brings every Goblin in the graveyard back to play. And with cards like Goblin Warchief and Siege-Gang Commander, those Goblins have haste and bring friends with them! A resolved Patriarch’s Bidding is usually game over.

https://scryfall.com/card/wc03/pk0a

Hometown hero Peer Kröger played his own version of the classic “Reanimator” deck to an impressive record during this year's World Championships. The twenty-eight-year-old communications and computer science student nicknamed his deck “Herbert Wise” after the famous H. P. Lovecraft work “Herbert Wise—Reanimator.” Winning with this deck is a two-step process: Step 1. Use Entomb or Buried Alive to quickly get daunting creatures into the graveyard. Step 2. Bring the creature back to life with Zombify or Doomed Necromancer. The mostly black deck also uses Burning Wish to find just the right answers to deal with opponents’ plans.

https://scryfall.com/card/wc03/dh0a

The Top 8 is familiar territory for professional Magic player Dave Humpherys. With over $130,000 in career winnings and a Pro Tour championship on his resume, “The Hump” advanced to the Worlds semifinals for the second year in a row where he lost to eventual champion Daniel Zink. The blue-green madness deck he played has been a Standard mainstay for more than a year. It revolves around Torment madness cards like Basking Rootwalla and Circular Logic, together with discard-enablers like Aquamoeba and Wild Mongrel. Humpherys, who recently earned his Ph.D. from MIT, credits this version of the deck to Norway’s Sigurd Eskeland.

https://scryfall.com/card/wc01/tvdl0a

Tom van de Logt is the 2001 Netherlands National Champion as well as one of an elite group of players who have posted back-to-back World Championship Top 8 performances. Currently a student in Groesbeek, van de Logt posted an impressive 5–1 record in the Standard portion of this year’s Worlds. He described his aggressive black-red “Machine Head” deck as “the deck that beats the deck that beats ‘Fires.’” He liked the explosive “I win” draws that his deck provided, and he especially liked the way it performed against blue decks.

https://scryfall.com/card/wc01/jt0a

Jan Tomcani, from Bratislava in the Slovak Republic, came out of nowhere to stun everyone by posting a perfect 6–0 record in the Standard portion of this year’s Worlds. Tomcani then proved that his run was no fluke by working his way up to the quarterfinals, where he lost to Alex Borteh in a close five-game match. Tomcani played a version of “Fires,” the green-red deck that defined much of this year's metagame. Tomcani’s version, which splashed black, follows the normal Fires archetype of playing cheap creatures followed by Fires of Yavimaya and big creatures like Blastoderm or Spiritmonger.

https://scryfall.com/card/wc01/ar0a

A member of the famous Team Block Ops, Antoine Ruel, a native of Aubervilliers, France, took his blue-black-red control deck to a third-place finish at this year’s World Championships. Ruel credits his teammate Laurent Pagorek for the deck that he calls “AK-Go.” The deck, which Ruel played to a 5–1 record during the Standard portion of the tournament, relies on card drawing (most notably Accumulated Knowledge, or “AK” for short), countermagic (“Go,” for short), red for board control, and Nether Spirits for the win.

https://scryfall.com/card/wc01/ab0a

Eighteen-year-old Alex Borteh came on strong in the last half of the 2000–2001 Pro Tour™ season. He posted an impressive Top 8 finish at U.S. Nationals and followed that up by coming within one match of winning this year’s Worlds. The soon-to-be Ohio State University freshman played a monoblue combo deck that he liked to call “Da Folk.” This deck wins by using Opposition and Static Orb to establish a lock down while legions of Merfolk overrun opponents’ immobilized defenses.

https://scryfall.com/card/wc00/tvdl0a

Quarterfinalist Tom van de Logt posted a perfect 6–0 record during the Standard portion of this year’s World Championships. The 19-year-old Groesbeek, Holland native was playing a deck that had a big impact on the metagame this year, “Replenish.” This deck used cards like Attunement and Frantic Search to put powerful enchantments, such as Parallax Wave and Opalescence, into the graveyard and then used Replenish to put them all back into play at once.

https://scryfall.com/card/wc00/nl0a

The 2000 World Championships was Nicolas Labarre’s third Top 8 finish at a Pro Tour™ event (Rome ’98, New York ’99, Worlds ’00). This Rennes, France native played a combo deck that he called “Chimera.” This deck used searching cards like Academy Rector and Enlightened Tutor to fetch Fecundity, Saproling Cluster, and Ashnod’s Altar. Once those three cards were in play, Labarre could generate as much mana as he wanted. With unlimited mana, he could play a very big Blaze or use Whetstone to immediately deck his opponent.

https://scryfall.com/card/wc00/jk0a

Hannover, Germany native Janosch Kühn joined an elite group of players in earning his second World Championship Top 8. Kühn played a red-green deck known as “Angry ’Derm” or “Son of Hermit.” The deck built up its mana early with Birds of Paradise or Llanowar Elves, and then followed that up with mana-denial cards like Stone Rain, Plow Under, and Avalanche Riders. Masticore and Blastoderm provided the finishing punch.

https://scryfall.com/card/wc00/jf0a

“World Champion” was the one honor Jon Finkel had yet to claim. His dominating performance at this year’s World Championships earned him that title at lost. Finkel played an explosive deck that is named after its most important card, Tinker. Fellow Team Antarctica member Dan O’Mahoney-Schwartz designed this monoblue deck. The deck used artifacts such as Grim Monolith, Metalworker, and Voltaic Key to quickly generate huge amounts of mana, and then used that mana to put large creatures into play.

**Comment by gmac** [comment]
These are all entered. Thanks!
