### ISSUE TITLE
Keyword to return prints in all languages

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#836]
There should be a keyword to return prints in all languages. A hacky way of almost doing this is `-lang:px`.

Maybe add this functionality to the `include:` keyword? (`include:foreign`, `include:langs`)

Maybe add this functionality to the `lang:` keyword? (`lang:all`)

**Comment by csuhta** [comment]
`lang:*` and `lang:all` and `lang:any` are already available 😀

**Comment by NilsEnevoldsen** [comment]
Oh wow. 😂

**Comment by NilsEnevoldsen** [comment]
New request: document that!
