### ISSUE TITLE
Battlebond tokens mistakenly under CM2

### ISSUE THREAD

**Issue by ancestral** [scryfall/feedback#839]
Battlebond tokens mistakenly under CM2
https://scryfall.com/sets
<img width="1069" alt="screen shot 2018-06-02 at 8 37 00 pm" src="https://user-images.githubusercontent.com/735024/40882358-f6055e4c-66a4-11e8-8cbb-6a17a280cd3a.png">

**Comment by csuhta** [comment]
Fixed
