### ISSUE TITLE
CN2 Conspiracy 2: Take the Crown was printed in Chinese Simplified and Japanese

### ISSUE THREAD

**Issue by ancestral** [scryfall/feedback#843]
Scryfall is missing references and renders to Chinese Simplified and Japanese for Conspiracy 2.

https://scryfall.com/card/cn2/126
http://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=416883

**Comment by csuhta** [comment]
CN2's localizations have been imported: https://scryfall.com/search?as=&q=e%3Acn2%20unique%3Aprints%20lang%3Aany
