### ISSUE TITLE
Add language column to pricelist display

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#845]
https://scryfall.com/search?q=lang:*+cn:1+s:tsb+unique:prints+display:list

This is not a very useful display format without a language column.

<img width="1032" alt="screen shot 2018-06-07 at 12 15 09 am" src="https://user-images.githubusercontent.com/222743/41077972-e028dbee-69e7-11e8-96da-13da4b583af5.png">

**Comment by csuhta** [comment]
Added: https://scryfall.com/search?q=e%3Adom+lang%3Aany+as%3Apricelist+unique%3Aprints
