### ISSUE TITLE
Oracle text symbol errors in non-English prints

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#849]
I know you don't want to commit to fully supporting "proper" foreign Oracle text, but fixing these types of errors can be done efficiently, affects a huge number of cards, and significantly improves the display of the cards it affects.

https://scryfall.com/search?q=o:/\bo(\d|\d\d|cT|T|W|G)\b/+unique:prints+lang:all

That gets many of them, but oU, oB, and oR return false positives. A case-sensitive regex would help.

Also it doesn't hit chains of symbols, like o3oGoG.

I'm not sure if other symbols are affected.

**Comment by csuhta** [comment]
All of the odd `oU` symbols and friends have been replaced
