### ISSUE TITLE
Direction parameter has no effect over result order when `order:` is specified as keyword.

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#854]
Direction parameter has no effect over result order when `order:` is specified as keyword.

https://scryfall.com/search?q=cn=1+order:date&order=released&dir=asc

https://scryfall.com/search?q=cn=1+order:date&order=released&dir=desc

Omitting order parameter makes no difference.

https://scryfall.com/search?q=cn=1+order:date&dir=asc

https://scryfall.com/search?q=cn=1+order:date&dir=desc

Direction parameter has expected effect over result order when order isn't specified as keyword.

https://scryfall.com/search?q=cn=1&order=released&dir=asc

https://scryfall.com/search?q=cn=1&order=released&dir=desc

**Comment by csuhta** [comment]
Fixed!
