### ISSUE TITLE
List of colorless tokens that should be colored

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#857]
https://scryfall.com/search?q=c%3Ac+t%3Acreature+not%3Adoublesided+-morph+-manifest+-t%3Aartifact+-t%3Aeldrazi+-t%3Asliver+-t%3Ashapeshifter+-t%3Adragon+-s%3Atdag+-s%3Atbth+-s%3Atfth+%2B%2B

This search finds colorless tokens that should be colored.

Note that it also pulls in some truly colorless Spirit tokens.

**Comment by csuhta** [comment]
Fixed: https://scryfall.com/search?q=c%3Ac+t%3Acreature+not%3Adoublesided+-morph+-manifest+-t%3Aartifact+-t%3Aeldrazi+-t%3Asliver+-t%3Ashapeshifter+-t%3Adragon+-s%3Atdag+-s%3Atbth+-s%3Atfth+%2B%2B
