### ISSUE TITLE
Token coloring is inconsistent

### ISSUE THREAD

**Issue by spacemonaut** [scryfall/feedback#858]
Some tokens are marked as colorless, despite ostensibly being colored:  https://scryfall.com/search?q=is%3Atoken+c%3Ac+t%3Acreature&unique=cards&as=grid&order=name

Other tokens are colored: https://scryfall.com/search?q=is%3Atoken+-c%3Ac+t%3Acreature&unique=cards&as=grid&order=name

There doesn't appear to be a particular reason why some white angels are white and some white angels show up colorless.

It would be fair to go either way. If angels are created white, it's fair to make the search consider them white. If the token itself has no color information (frames don't define a color) it is also take to make the search consider tokens colorless.

**Comment by csuhta** [comment]
Ok, these have been cleaned up and these results are correct now:
https://scryfall.com/search?as=grid&order=name&q=is%3Atoken+c%3Ac+t%3Acreature+-e%3Atust&unique=cards
