### ISSUE TITLE
Use Japanese language/text for PDD2

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#859]
https://scryfall.com/sets/pdd2 uses English Oracle text and reports the prints as English.

Copy the Japanese text from https://scryfall.com/card/lrw/159/ja and https://scryfall.com/card/lrw/71/ja.

~~(Alternatively, move the promos into PDD?)~~ This made no sense. Ignore me.

**Comment by NilsEnevoldsen** [comment]
This is partially fixed. The cards are now in Japanese, but are still reported as EN.

**Comment by csuhta** [comment]
Fixed
