### ISSUE TITLE
Change collector number sort from numeric to alphanumeric

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#861]
The current collector number sort is numeric rather than alphanumeric:

<img width="259" alt="screen shot 2018-06-16 at 5 06 01 pm" src="https://user-images.githubusercontent.com/222743/41502411-99667b7e-7187-11e8-9c4c-11ba6859e3ba.png">

I think it would be better as alphanumeric, although there may be a use case I haven't considered.

**Comment by csuhta** [comment]
Number sorting sorts by numeric collector number, then alphabetical, which is for these much more common situations:

<img width="660" alt="en7uszzlra" src="https://user-images.githubusercontent.com/769083/41502953-a57f5fe0-7194-11e8-8a20-7a4ccae96dc8.png">

The deck/Collector sets are an annoying outlier, but they're not really worth optimizing for.

**Comment by NilsEnevoldsen** [comment]
Just to clarify, the proposed sort would yield the same sort for the examples you give.

**Comment by csuhta** [comment]
No, a pure alphabetical sort looks like this:

<img width="369" alt="f9knltkkp9" src="https://user-images.githubusercontent.com/769083/41503162-4fde302e-719a-11e8-931d-043cdaf1d88d.png">

**Comment by NilsEnevoldsen** [comment]
It appears the terminology is a bit mixed. I'm referring to ["natural sort order"](https://en.wikipedia.org/wiki/Natural_sort_order) or ["alphanum"](http://www.davekoelle.com/alphanum.html). "Alphabetical" or "ASCIIbetical" is indeed what you have given. "Alphanumeric" is not well defined. I'll change the title of the issue.

(I realize that it may still not be worth optimizing for.)
