### ISSUE TITLE
/cards/:code/:number Endpoint Broken for Unstable Cards with Multiple Versions

### ISSUE THREAD

**Issue by kylejrp** [scryfall/feedback#865]
A 404 response is returned when searching for [these cards](https://scryfall.com/search?q=%2B%2B+set%3Aust+%28%22Amateur+Auteur%22+or+%22Knight+of+the+Kitchen+Sink%22+or+%22Novellamental%22+or+%22Very+Cryptic+Command%22+or+%22Extremely+Slow+Zombie%22+or+%22Sly+Spy%22+or+%22Garbage+Elemental%22+or+%22Target+Minotaur%22+or+%22Beast+in+Show%22+or+%22Ineffable+Blessing%22+or+Everythingamajig+or+Killbot+or+%22Secret+Base%22%29&order=set).

For example:
[https://api.scryfall.com/cards/ust/3](https://api.scryfall.com/cards/ust/3)

**Comment by csuhta** [comment]
These cards include letters in their collector numbers. The letters are required:

https://api.scryfall.com/cards/ust/3a
https://api.scryfall.com/cards/ust/3b

etc

**Comment by kylejrp** [comment]
Thanks! I had assumed it was the printed collector number and didn't realize that the Scryfall collector number could be different.

**Comment by csuhta** [comment]
Normally we do try to match the numbers on the cards, but it's not feasible for every set.

Some other common exceptions:

- Sets printed before collector numbers were a thing have Scryfall numbers that we made up
- Many promo cards simply have `001` printed on the card. Scryfall has had to create other numbers for these cards. 
- Some sets have foil variants, we add a star to these collector numbers
