### ISSUE TITLE
Documentation mispellings in /docs/api/cards

### ISSUE THREAD

**Issue by kylejrp** [scryfall/feedback#866]
https://scryfall.com/docs/api/cards

    This card’s overall rank/popularity on EDHREC. Not all carsd are ranked.
carsd -> cards

    An object listing available imagery for this card. See the [Card Imagery](#) article for more information.
Link is broken

    A URL to this cards’s story article, if any.
cards's -> card's

**Comment by gmac** [comment]
fixed in next release
