### ISSUE TITLE
Æ and æ ligatures substituted in flavor text

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#870]
`Æ` and `æ` ligatures in Gatherer flavor text have become `Ae` and `ae` in Scryfall.

Pay special attention to https://scryfall.com/card/unh/50, as in #627.

**Comment by gmac** [comment]
See note on spelling in https://mtg.gamepedia.com/Aether.

```
Although Wizards of the Coast used the ligature Æ — the A and E combined into one letter — since the beginning of the game, this was changed for Kaladesh and Aether Revolt, which featured the stuff heavily. According to Blake Rasmussen, it caused way more issues than it was worth (particularly in translation). [11] The change is retroactive. [12]
```

http://markrosewater.tumblr.com/post/144471532728/this-is-a-bit-weird-but-i-notice-its-the-aether

You could debate that this specifically applies to card names, but we've been following it for all texts. The ligature is an alias for `ae` in search https://scryfall.com/search?q=o%3A%22%C3%86%22

**Comment by csuhta** [comment]
@gmac This was only a change for card names. Flavor text does continue to have the ae markers, especially [Bloodletter](https://scryfall.com/card/unh/50) which uses as a joke.

**Comment by gmac** [comment]
The AE ligature is now supported in flavor texts! https://scryfall.com/card/unh/50
