### ISSUE TITLE
[M19] "Liliana, Untouched by Death" not found in boosters

### ISSUE THREAD

**Issue by spider312** [scryfall/feedback#872]
Searching "e:m19 is:booster Liliana" doesn't returns Liliana, Untouched by Death

**Comment by spacemonaut** [comment]
Can reproduce. Only Liliana's Contract appears.

**Comment by NilsEnevoldsen** [comment]
Notably, Liliana appears to be the only card so misclassified: https://scryfall.com/search?q=s:m19+not:booster+display:list+order:set

**Comment by csuhta** [comment]
Fixed
