### ISSUE TITLE
[M19] Basic lands not found in boosters 

### ISSUE THREAD

**Issue by spider312** [scryfall/feedback#873]
While using API, when searching "e:m19 is:booster", only one basic land of each type is returned, despite 4 of each are returned with search_uri

**Comment by spacemonaut** [comment]
This is as designed: Scryfall by default only shows you one print for each card. If you set your filters to **Find: All prints** you get all 20 basic lands: https://scryfall.com/search?q=e%3Am19+is%3Abooster+t%3Abasic&unique=prints&as=grid&order=name&dir=

**Comment by csuhta** [comment]
@spacemonaut is correct
