### ISSUE TITLE
Failing to exclude instants

### ISSUE THREAD

**Issue by JineteDV** [scryfall/feedback#875]
The entire search string is: (-t:Instant, -t:Sorcery) (c:R OR c:C) cmc>=2 cmc<=3 f:legacy

![scryfff](https://user-images.githubusercontent.com/6514656/42096920-a4be8f78-7b84-11e8-9f84-9490db6bebf9.png)

**Comment by spacemonaut** [comment]
Terms don't get comma separated, write `(t:instant t:sorcery)` instead.

You wrote `-t:Instant,`. That looks for cards that don't have `Instant,` in their type line, which excludes zero cards.
