### ISSUE TITLE
API Documentation/data inconsistencies

### ISSUE THREAD

**Issue by Bardiches** [scryfall/feedback#876]
Been trying to work with the Scryfall API and through comparing the API documentation (https://scryfall.com/docs/api/) with actual API results, I've found a few inconsistencies. This isn't an exhaustive list.
- [x] Double sided cards (at least the few that I checked such as Village Ironsmith, Garruk Relentless, and Arguel's Blood fast) are missing the `mana_cost` field in the primary card object, although the appropriate object for the front side within the `card_faces` field has it. If this is intended, `mana_cost` should be documented as nullable on the primary card object.
- [x] Pricing fields (`usd`, `eur`, and `tix`) are entirely undocumented.
- [x] URI fields relating to other sites (`related_uris` and `purchase_uris`) are entirely undocumented.
- [x] Fields relating to card fields of specific printings (`printed_name`, `printed_type_line`, `printed_text`) are missing in the primary card object and within objects in the `card_faces` field. If this is intended, they should be documented as nullable.
- [x] The `object` field is undocumented on all objects that have it as a field (primary card objects, card faces, "related cards"). Possibly values for this should be documented along with what objects it can exist on.
- [x] Documentation mentions a `related_cards` field, but doesn't seem to be in use although this may be referring to the `related_card` type used on the undocumented `object` field
- [x] `legalities` field doesn't have a documented list of possible legalities (appears to be `legal`, `not_legal`, `restricted`, and `banned`).

All of these can be seen on Garruk Relentless (https://api.scryfall.com/cards/b4160322-ff40-41a4-887a-73cd6b85ae45).

**Comment by gmac** [comment]
updates shipped
