### ISSUE TITLE
/cards/search API - Option to return only IDs to help with caching?

### ISSUE THREAD

**Issue by kylejrp** [scryfall/feedback#879]
I'm writing a card collection management tool using the Scryfall API. I'm storing card objects from the API in my own database.

I'd like to leverage the /cards/search endpoint to help search the user's collection using Scryfall's syntax. However, using the /cards/search endpoint doesn't let an API user take advantage of their cached data. I'm worried that implementing this feature is taxing on the API, especially when there are multiple pages in a search.

I think it would be useful to have an extra flag that would make the endpoint only return IDs. This is kind of similar to the /cards/autocomplete endpoint which only returns card names. An example response for `GET` `https://api.scryfall.com/cards/search?order=cmc&q=c%3Ared+pow%3D3&only_ids=true`  might be:

```
{
  "object": "list",
  "total_cards": 423,
  "has_more": false,
  "data": [
      "c7e6915b-2077-45aa-93e7-29b5f14beb51",
      "4dfcc240-9010-4e0c-afda-7f70c42da7d2",
   ...
  ]
}
```

Here's how it works right now:
* Perform the user's search
  * `GET` `https://api.scryfall.com/cards/search?order=cmc&q=c%3Ared+pow%3D3` (77.7KB)
  * `GET` `https://api.scryfall.com/cards/search?order=cmc&q=c%3Ared+pow%3D3&page=2` (74.8KB)
  * `GET` `https://api.scryfall.com/cards/search?order=cmc&q=c%3Ared+pow%3D3&page=3` (32.9KB)
* Store those responses in my local database since we just got returned fresh data
* Get a list of all the IDs in the above responses
* Use those as keys to my local database

My proposed feature:
* Perform the user's search
  * `GET` `https://api.scryfall.com/cards/search?order=cmc&q=c%3Ared+pow%3D3&only_ids=true` (~20KB?) 
* Get a list of all the IDs in the above response
* Use those as keys to my local database

**Comment by csuhta** [comment]
@kylejrp This is a bit too specific to your use case for us to add to the API right now. 

You are free to implement any kind of caching strategy you want here (and we encourage it)

- You can call our API endpoints and cache everything 
- Or you can inspect only the `id` fields and default to using your local data if you already have a copy of that object

You are definitely not overtaxing our API here. Supporting the creation / operation of new MTG apps is a core goal of ours, and our API server caches its own data in several ways.

**Comment by kylejrp** [comment]
@csuhta Thanks, I really appreciate your detailed response and mentioning that I'm not a gross overtaxing API use case.

Thanks for everything you guys do!
