### ISSUE TITLE
Card images don't use transparent backgrounds

### ISSUE THREAD

**Issue by pt** [scryfall/feedback#883]
Not a bug per se, but images fetched from the API (e.g. normal_image) use white backgrounds for black-bordered cards, and black backgrounds for white-bordered cards. This makes it hard to use them in certain contexts (see image). It would be awesome if the area outside the card border were transparent.

<img width="385" alt="screen shot 2018-07-10 at 8 56 07 am" src="https://user-images.githubusercontent.com/9081/42522091-24aabf70-841f-11e8-98ec-b2fb6a9bf961.png">

**Comment by NilsEnevoldsen** [comment]
The high-resolution `png` image supports transparency. All other provided images are JPEGS, a format that does not support transparency.

I think Scryfall should consider adding a lossy format with transparency, such as WEBP, but one of the nice use cases would be the appearance of black-bordered cards in dark-mode Discord, and white-bordered cards in light-mode Discord, and not all Discord clients support WEBP.

Another potential option would be providing a smaller transparent PNG with more compression (such as a reduced color palette).

**Comment by csuhta** [comment]
@pt Please use the `png` format if you need transparent edges in the image file.

If you're building a web page or similar with the `large` version, you will need to apply a border radius to elements. Scryfall uses `border-radius: 4.75% / 3.5%` for standard corners.

@NilsEnevoldsen I do want to eventually want to support `webp`, but unfortunately it is still very much in its infancy. It will probably be a few years at minimum before it's popular enough. https://caniuse.com/#feat=webp

**Comment by pt** [comment]
Border radius is a really clever idea. Thanks.
