### ISSUE TITLE
List of prints with æ in flavor text

### ISSUE THREAD

**Issue by NilsEnevoldsen** [scryfall/feedback#885]
Now that #870 is fixed, we have the following prints with æ in flavor text:

- [x] https://scryfall.com/card/leg/131
- [x] https://scryfall.com/card/dis/104
- [x] https://scryfall.com/card/unh/50
- [x] https://scryfall.com/card/dpa/2
- [x] https://scryfall.com/card/ons/80
- [x] https://scryfall.com/card/plc/156
- [x] https://scryfall.com/card/m13/50
- [x] https://scryfall.com/card/m14/55
- [x] https://scryfall.com/card/med/93
- [x] https://scryfall.com/card/5dn/31
- [x] https://scryfall.com/card/rav/51
- [x] https://scryfall.com/card/cn2/111
- [x] https://scryfall.com/card/8ed/252
- [x] https://scryfall.com/card/bng/16
- [x] https://scryfall.com/card/rav/54
- [x] https://scryfall.com/card/pls/110
- [x] https://scryfall.com/card/wwk/127
- [x] https://scryfall.com/card/arc/111
- [x] https://scryfall.com/card/mm2/219
- [x] https://scryfall.com/card/ths/54
- [x] https://scryfall.com/card/8ed/311
- [x] https://scryfall.com/card/4ed/95
- [x] https://scryfall.com/card/leg/67
- [x] https://scryfall.com/card/bng/49
- [x] https://scryfall.com/card/lrw/92
- [x] https://scryfall.com/card/7ed/167
- [x] https://scryfall.com/card/me3/184
- [x] https://scryfall.com/card/leg/267
- [x] https://scryfall.com/card/10e/122
- [x] https://scryfall.com/card/m10/79
- [x] https://scryfall.com/card/dpa/17

**Comment by gmac** [comment]
all set.

**Comment by NilsEnevoldsen** [comment]
Bless you!
