### ISSUE TITLE
Variant on o: to ignore ~

### ISSUE THREAD

**Issue by breadbocks** [scryfall/feedback#888]
A version of rules text search that ignores the card name would be incredibly useful. The desired syntax would function along the lines of "o:Foo -o:~" but without excluding cards with Foo in the name that both refer to themselves in the rules text and also to Foo. 

Example case: "o:merfolk" includes Benthicore (Refers to itself as well as merfolk generically) and Jolting Merfolk (Just refers to itself) while "o:merfolk -o:~" does not. The requested syntax, #:merfolk would return Benthicore but NOT Jolting Merfolk. 

This syntax would be incredibly useful for locating tribal synergies, particularly with tribes that commonly occur in creature names.

**Comment by csuhta** [comment]
@breadbocks This is a bit too specific for your use-case to make into a search feature right now. When brewing you can simply ignore these results.
