### ISSUE TITLE
Advanced Search Multiple Stats

### ISSUE THREAD

**Issue by jamesrichter** [scryfall/feedback#90]
For example: searching for a creature with CMC < 3 and Toughness > 3.

It can be done in URL but not from page form on Advanced Search page.

**Comment by csuhta** [comment]
Sorry, this was available but broken. Fixed now! 

![obviouswaryhatchetfish](https://cloud.githubusercontent.com/assets/769083/26759352/4c8f38be-48c9-11e7-80a3-52fe50c319c0.gif)
