### ISSUE TITLE
Filters for sets

### ISSUE THREAD

**Issue by razielsarafan** [scryfall/feedback#91]
I'd like to be able to filter out MTGO-only sets from the API (Tempest Remastered, Treasure Chests, etc) from the list of sets, so I can get a list of all the sets that are actually printed in paper.

**Comment by gmac** [comment]
You're looking for `-is:online`, which is the negated form of the `is:online` filter.

https://scryfall.com/search?q=-is%3Adigital

**Comment by gmac** [comment]
Apologies! I skimmed that you are looking to filter sets, not cards.

**Comment by gmac** [comment]
You should be all set. The sets API now includes a `digital` property that you can filter results on. https://api.scryfall.com/sets

Thanks for the report. Happy hacking!
