### ISSUE TITLE
Transform Cards not showing "A" side

### ISSUE THREAD

**Issue by defbyte** [scryfall/feedback#96]
When viewing the transformed side of a card, clicking the transform button doesn't show the "A" side (non-transformed side). Visually, the card flips, but it is the same image.

Appears to be specific to `is:transform` cards, when viewing the B-side.

![transform-flip-bug](https://cloud.githubusercontent.com/assets/338892/26815541/f6619c96-4a5a-11e7-9ebe-44a42f238853.gif)

**Comment by gmac** [comment]
DOH! Right, that was a stupid oversight when hooking in Meld cards.

**Comment by gmac** [comment]
This is fixed. https://scryfall.com/search?as=full&q=is%3Atransform
